2단계 - 문자열 덧셈 계산기 🐳
g-oop/goop-java-racingcar pull request #10
Opened 2024-01-11 00:03 UTC by Ppojin

계산기 구현되어 PR 올립니다~

![스크린샷 2024-01-11 오전 9 03 04](https://github.com/g-oop/goop-java-racingcar/assets/25076967/3e67b221-2bf5-4d62-aeab-8ef314021aca)


2024-01-13 14:50 UTC, nooose requested changes
안녕하세요 뽀진님 ㅋㅋ
제가 대신 맡게 되었습니다. 🥲
읽어보시고 재요청 부탁드려요~

2024-01-13 14:50 UTC, nooose commented on src/main/java/com/ppojin/util/StringUtils.java
>      }
그대로 `문자열.split(delimiter)`를 사용하는 것과 같아보이는데
유틸 클래스에 있는 `splitByDelimiter`는 불필요하지 않을까요?

2024-01-13 14:50 UTC, nooose commented on src/main/java/com/ppojin/util/StringUtils.java
> +    }
파라미터 이름이 num이네요 
value 같은 다른 변수명이 적절해보여요

2024-01-13 14:50 UTC, nooose commented on src/main/java/com/ppojin/util/StringUtils.java
>      public static String removeBracket(String t){
파라미터를 봤을 때 무슨 파라미터인지 알 수 있도록 이름을 변경하면 좋을 것 같네요
미션 끝까지 변수명 하나하나에 의미를 부여하면 좋을 것 같습니다.

이전 단계에서 사용한 메소드 같은데 겸사겸사 리뷰 남겨봤습니다.

2024-01-13 14:50 UTC, nooose commented on src/test/java/com/ppojin/util/StringAddCalculatorTest.java
> +    }
```suggestion
    @NullAndEmptySource
    @ParameterizedTest
    public void splitAndSum_null_또는_빈문자(String input) {
        int result = StringAddCalculator.splitAndSum(input);
        assertThat(result).isEqualTo(0);
    }
```

`ParameterizedTest`를 사용하면 중복코드를 제거할 수 있습니다.

나머지 테스트케이스에도 적용할 수 있어보여요

2024-01-13 14:50 UTC, nooose commented on src/main/java/com/ppojin/util/StringAddCalculator.java
> +        final String[] nums = StringUtils.splitByDelimiter(text, delimiter);
코드를 보면 delimiter를 기준으로 토큰 배열을 구하는 것 같네요.
이 부분을 메서드로 추출하면 더 가독성있는 코드가 될 것 같습니다.

- 예시
```java
private static String[] split(String text) { // 정규식 사용 로직 포함 }
```

2024-01-13 14:50 UTC, nooose commented on src/main/java/com/ppojin/util/StringAddCalculator.java
> +        final String[] nums = StringUtils.splitByDelimiter(text, delimiter);
호출하는 유틸 메서드 명이 splitAndSum 이니까

```java
    public static int splitAndSum(String text) {
        if (StringUtils.isEmpty(text)) {
            return 0;
        }

        final String[] nums = split(text);

        return Arrays.stream(nums)
                .map(StringAddCalculator::parseIntExceptNegative)
                .mapToInt(i -> i)
                .sum();
    }
```
이렇게도 변경해 볼 수 있을 것 같아요

2024-01-13 14:50 UTC, nooose commented on src/main/java/com/ppojin/util/StringAddCalculator.java
> +    }
s, n 같이 변수를 줄이지 않고 의미있는 이름으로 변경하면 좋을 것 같아요

2024-01-13 14:50 UTC, nooose commented on src/main/java/com/ppojin/util/StringAddCalculator.java
> +        Matcher m = Pattern.compile(CUSTOM_DELIMITER_CONVENTION).matcher(text);
계산기를 호출할 때 마다 정규식을 매번 컴파일하겠네요.
정규식 비용은 비싸기 때문에 고정된 값이라면 패턴 자체를 상수화시키는 것이 좋습니다.

<img width="585" alt="image" src="https://github.com/g-oop/goop-java-racingcar/assets/36617783/aac31e95-968e-4466-9f25-a1f7846f932a">

```suggestion
        Matcher matcher = PATTERN.matcher(text);
```

2024-02-08 01:26 UTC, yamsroun commented
@Ppojin 수정 반영 안된지 오래되었네요~
2월 말까지 얼마 안 남았어요~
조금만 더 달려봅시당~

2024-07-04 15:15 UTC, closed without merging