2단계 - 문자열 덧셈 계산기
g-oop/goop-java-racingcar pull request #19
Opened 2024-01-15 00:54 UTC by mzueon

- 1단계 코드 수정
- 문자열 덧셈 계산기 클래스 & 테스트 작성

2024-01-15 04:04 UTC, gilbertlim commented on src/test/java/racingcar/stringcaculator/StringAddCalculatorTest.java
> +    void calculateBlank() {
Null, Empty String을 ParameterizedTest로 사용할 수 있어요.
반복마다 input에 null, ""이 입력돼요! 
```java
    @ParameterizedTest
    @NullAndEmptySource
    void calculateBlank(String input) {
```

2024-01-15 04:06 UTC, gilbertlim commented on src/test/java/racingcar/stringcaculator/StringAddCalculatorTest.java
> +    }
요구사항 6. 음수를 전달할 경우 RuntimeException 예외가 발생해야 한다. (예 : “-1,2,3”)

요구사항에 대한 테스트가 누락되었네요!

2024-01-15 04:08 UTC, gilbertlim commented on src/main/java/racingcar/stringcalculator/StringAddCalculator.java
> +            Matcher m = Pattern.compile(CUSTOM_DELIMITER_PATTERN).matcher(text);
Pattern.compile 메서드는 내부적으로 Pattern 객체를 생성해요. 상수 처리하여 캐싱하면 비용을 아낄 수 있을거에요~

2024-01-15 04:11 UTC, gilbertlim commented on src/main/java/racingcar/stringcalculator/StringAddCalculator.java
> +        return text.split(DEFAULT_DELIMITER);
split 메서드가 중복으로 사용되네요.
학습 차원으로 공통으로 사용할 수 있는 지 고민해볼까요?

2024-01-15 04:13 UTC, gilbertlim commented on src/main/java/racingcar/stringcalculator/StringAddCalculator.java
> +            numbers[i] = parseIfNumeric(tokens[i]);
split()와 달리 parseInt 메서드를 공통으로 사용하게끔 메서드를 따로 추출했네요?
그렇지만 parseIfNumeric()을 중복으로 call하고 있습니다.

숫자 변환을 한 번만 하여 덧셈할 순 없을까요?

2024-01-15 04:15 UTC, gilbertlim commented on src/main/java/racingcar/stringcalculator/StringAddCalculator.java
> +    private static boolean isBlank(String text) {
메서드 분리👍

2024-01-15 04:22 UTC, gilbertlim commented on src/main/java/racingcar/stringcalculator/StringAddCalculator.java
> +        validate(tokens);
validate(tokens) 메서드를 호출하지 않아도 모든 TC를 통과합니다.

sum() 메서드 내부적으로 parseIfNumeric()이 호출되면서 숫자가 아닌 값에 대한 validation은 되고 있어요.
parseIfNumeric()에서 음수 체크까지 해준다면 중복 로직을 제거할 수 있을 것 같아요.

2024-01-15 04:25 UTC, gilbertlim requested changes
코멘트 확인 후 다시 리뷰 요청해주세요!

2024-01-16 13:49 UTC, mzueon commented on src/main/java/racingcar/stringcalculator/StringAddCalculator.java
> +        validate(tokens);
파싱과 음수 체크를 따로 분리해서 메서드별로 역할을 분리하려고 해봤던건데, 뭔가 기준(?)을 잘못 잡았나 봅니다 ㅎㅎ.. 오히려 중복로직이 생기는 점을 고려하지 못했네요!

2024-01-17 01:11 UTC, gilbertlim commented on src/main/java/racingcar/stringcalculator/StringAddCalculator.java
> +    private static final Pattern pattern = Pattern.compile(CUSTOM_DELIMITER_PATTERN);
상수는 관례적으로 대문자와 언더바를 사용해요 !

2024-01-17 01:18 UTC, gilbertlim commented on src/main/java/racingcar/stringcalculator/StringAddCalculator.java
> +        }
Matcher class의 Javadoc을 읽어보세요!
아래와 같이 사용하면 된답니다~
```java
        Matcher m = pattern.matcher(text);
        if (m.find()) {
            delimiter = m.group(1);
            text = m.group(2);
        }
```

2024-01-17 01:22 UTC, gilbertlim approved these changes
너무 잘해주셔서 별로 코멘트할 게 없네요.
몇 개 남겼는데, 확인해주시고

다음 단계 진행해주세요~

2024-01-17 01:23 UTC, merged