3단계 - 자동차 경주
g-oop/goop-java-racingcar pull request #20
Opened 2024-01-19 15:34 UTC by boy0516

3단계 리뷰부탁드립니다.😅

2024-01-19 19:06 UTC, nooose requested changes
지훈님 첫빠따 추카드립니다.
제가 제대로 파악 못해서(졸려서 😅) 질문이랑 같이 코멘트 남겼어요
읽어보시고 이해 안 되는 부분 있으면 DM이나 코멘트 남겨주세요

2024-01-19 19:06 UTC, nooose commented on src/main/java/StringAddCalculator.java
> +        return text == null||text.isBlank();
```suggestion
        return text == null || text.isBlank();
```

2024-01-19 19:06 UTC, nooose commented on src/main/java/StringAddCalculator.java
> -            return Integer.parseUnsignedInt(text);
양수 체크를 위해서 Integer 클래스를 사용하는 대신
직접 구현한 이유가 있나요?
(진짜 궁금해서 물어보는 거임)

2024-01-19 19:06 UTC, nooose commented on src/main/java/StringAddCalculator.java
>      private StringAddCalculator() {}
<img width="256" alt="image" src="https://github.com/g-oop/goop-java-racingcar/assets/36617783/f712ed5c-1d00-43aa-a88b-13a8451b4b30">

문자열 계산기와 자동차 경주를 완전히 패키지 분리시키는 게 보기 좋을 것 같아요

---

원래있던 gitkeep 파일도 왜 있었는지 읽어보시면 좋을 것 같습니다.
https://computer-science-student.tistory.com/268

지금은 코드가 추가되었으니 이제는 제거해도 되겠네요

2024-01-19 19:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/view/InputViewTest.java
> +}
<img width="98" alt="image" src="https://github.com/g-oop/goop-java-racingcar/assets/36617783/b2360752-eab4-4bd9-8dc9-69e0f812b31f">

일부 클래스에서 빨간 경고가 나오네요
[블로그](https://velog.io/@jangws/EOL%EC%9D%84-%EB%84%A3%EC%96%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0%EC%99%80-git%EC%97%90%EC%84%9C-CRLF-EOL-%EC%B0%A8%EC%9D%B4%EB%A1%9C-%EC%9D%B8%ED%95%9C-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95) 읽어보시고 반영해 주세요

<img width="679" alt="image" src="https://github.com/g-oop/goop-java-racingcar/assets/36617783/a830a52c-2862-4d3b-b87a-709e66f0c009">

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepalyer/GamePlayer.java
> +    }
게임을 시작하는 main 클래스네요

```suggestion
    public static void main(String[] args) {
        RacingGamePack racingGamePack = new RacingGamePack();
        racingGamePack.play();
    }
```

GamePlayer를 인스턴스화 한 이유가 있나요?
제가 제안한 코드와 차이가 없어보여요 🤔

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepack/GamePack.java
> +public interface GamePack {
어떤 이유로 GamePack 인터페이스를 만들었는지 궁금합니다.

2024-01-19 19:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/vo/PositionTest.java
> +        assertThat(position.getPosition()).isEqualTo(1);
자동차 위치를 나타내는 값 객체를 만드셨네요
그러면 이렇게도 비교해볼 수 있을 것 같아요

```suggestion
        assertThat(position).isEqualTo(new Position(1));
```
equals를 구현하면서 hashcode도 같이 만들어두면 좋을 것 같습니다.

2024-01-19 19:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/vo/PositionTest.java
> +class PositionTest {
클래스에 DisplayName을 선언하면 테스트를 돌렸을 때
클래스 이름 대신 정의한 이름이 출력됩니다. 이러면 여러 테스트 케이스를 돌렸을 때 좀 더 쉽게 파악할 수 있어요.

- 예시
```suggestion

@DisplayName("도메인 - Position 테스트")
class PositionTest {
```
개인적인 의견이니까 참고만 해주세요

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/Car.java
> +    public int getPosition() {
메서드 사이는 한줄 개행이 좋은 것 같습니다.
```suggestion
    }

    public int getPosition() {
```

2024-01-19 19:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/entity/DriverTest.java
> +        assertThat(result).isBetween(0, 1);
drive는 동사라서 상태를 변경하는 행위로 보입니다.
자동차를 이동시킨 후 자동차의 위치를 꺼내서 비교하는 게 좀더 자연스러워 보이는데 어떻게 생각하시나요?

```suggestion
        Driver driver = new Driver();
        //when
        driver.drive();
        //then
        assertThat(driver.position()).isBetween(0, 1);
```

2024-01-19 19:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/entity/DriverTest.java
> +        assertThat(result).isBetween(0, 1);
자동차 위치가 0인지 1인지 제어가 되지 않아 between으로 테스트 케이스를 만들었네요
아마 랜덤 때문에 이런 코드가 나온 것 같아요

뒷부분에서도 리뷰 드리겠지만
랜덤 같이 제어할 수 없는 부분을 어떻게 테스트하면 좋을지 한번 고민해 보셨으면 좋겠습니다.

2024-01-19 19:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/entity/CarTest.java
> +    @DisplayName("초기 Car의 run 결과 테스트")
```suggestion
    @DisplayName("자동차 이동 테스트")
```
테스트 설명이 너무 애매한 것 같아요 정확하게 표현하면 좋을 것 같습니다.

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/Driver.java
> +    private final int MOVE_MIN = 4;
고정값인데 드라이버 마다 멤버변수로 가져갈 필요가 없어보입니다.
static 상수로 선언하는 게 좋습니다.

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/RacingTrack.java
> +    }
도메인 클래스가 출력 관련 기능을 의존하고 있네요
콘솔이 아닌 다른 출력 기능을 요구한다면 도메인 클래스도 같이 변경해야하는 문제가 생깁니다.
출력을 담당하는 클래스에서 도메인 객체를 받아 출력하도록 변경하는 것이 좋을 것 같아요

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/RacingTrack.java
> +    }
도메인이 출력을 의존하고 있는 것 같아요
도메인은 값만 제공하고 출력을 담당하는 쪽에서 해당 값을 사용하면 되지 않을까요?

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/view/ResultView.java
> +    }
자동차 출력 관련된 클래스인가요?
맞다면 생성자에서 자동차또는 드라이버를 받아서 처리하는 게 맞을 것 같아요.

```suggestion
    public ResultView(List<Car> cars) {
        // 로직
    }
```

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/view/ResultView.java
> +    }
TextView 인터페이스를 만드신 이유도 궁금합니다. 
답변 남겨주세요~

2024-01-19 19:06 UTC, nooose commented on src/main/java/gameboy/gamepalyer/console/InputConsole.java
> +    }
askUserInput 메서드를 봤을 때 TextView에 담긴 내용이 뭔지 모르는 상태에서 
int 값을 리턴하고 있는데 이럴바에는

`InputConsole.inputNumber(String text);`
`InputConsole.inputText(String text);` 
같은 메서드를 만들어두는 게 낫지 않나요?

2024-01-20 02:42 UTC, boy0516 commented on src/main/java/StringAddCalculator.java
> -            return Integer.parseUnsignedInt(text);
이건 별 이유는 없고요. 직접 해보라는 의돈가? 하는 생각에 그냥 해봤습니다.

2024-01-20 02:45 UTC, boy0516 commented on src/main/java/gameboy/gamepalyer/GamePlayer.java
> +    }
main이 GamePlayer 클래스에서 분리되어야하나? 하는 생각에 넣었는데 지금은 없는게 나아 보이네요

2024-01-20 03:12 UTC, boy0516 commented on src/main/java/gameboy/gamepack/GamePack.java
> +public interface GamePack {
GamePlayer에 GamePack의 play()만 호출하면 게임이 실행되도록 하려고 인터페이스 추가했습니다. 
추후 레이싱 게임 외에 다른 게임팩이 추가될 수 있다고 가정했을 때 GamePack의 구현체를 GamePlayer에 삽입해 play만 호출하면 게임이 실행되도록해야겠다고 생각해서 이렇게 작성했습니다.

2024-01-20 03:32 UTC, boy0516 commented on src/main/java/gameboy/gamepack/racinggame/view/ResultView.java
> +    }
지금은 입출력이 모두 텍스트로 이루어지니까 단순하게 TextView를 만들어서 display메서드의 반환값이 String으로 나가도록 강제하고 나중에 다른 입출력을 요구하는 콘솔에는 다른 인터페이스를 만들어서 display메서드의 반환 타입을 강제해야겠다고 생각해서 일단 만들었는데 지금 상황에선 딱히 필요없긴합니다

2024-01-20 03:47 UTC, boy0516 commented on src/main/java/gameboy/gamepalyer/console/InputConsole.java
> +    }
그래서 처음엔 InputView에 사용자 입력에 대한 반환 타입을 포함해서 보내서 inputConsole에서 분기처리를 했는데 지금은 입력이 숫자로 정해져있어서 쓸데없이 복잡해지는거같아가지고 뺐거든요.
inputNumber, inputText 메서드 만드는 방향으로하는게 나아보이나요?

2024-01-20 05:10 UTC, boy0516 commented on src/test/java/gameboy/gamepack/racinggame/data/vo/PositionTest.java
> +        assertThat(position.getPosition()).isEqualTo(1);
지금은 Position의 noArgs 생성자밖에 없는데 테스트 코드를 위해 생성자를 추가하는건 상관없나요??

2024-01-20 05:34 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/vo/PositionTest.java
> +        assertThat(position.getPosition()).isEqualTo(1);
이것도 항상 호불호가 갈리는 내용인데요
저는 개인적으로 필요하다면 생성할 수 있다고 생각합니다.

지훈님이 Position도 값이라고 판단해서 VO로 만들었을거에요 
그렇기 때문에 값은 언제든지 생성할 수 있다고 생각합니다.

그래도 외부에서 호출되는 게 좀 찝찝하다면 
default 접근 제한자를 사용해서 같은 패키지에서만 호출될 수 있는 생성자로 만들면 되지 않을까 싶네요
테스트 코드도 보통 같은 패키지에 생성하니까 괜찮을 것 같고요

```java
    public Position() {  }

    Position(int position) {
        this.position = position;
    }
```

2024-01-20 05:42 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/view/ResultView.java
> +    }
매번 모든 객체를 String으로 만들어서 반환하는 게 좀 힘들 것 같아요
타임리프나 JSP 같은 것을 써보셨으면 알겠지만
모델타입에 대한 강제성도 없고 어떻게 출력할지는 view에다가만 선언하면 됩니다.

2024-01-20 05:53 UTC, nooose commented on src/main/java/gameboy/gamepalyer/console/InputConsole.java
> +    }
추상화가 너무 섣부르다보니까 복잡해지는 것 같아요 
어차피 핵심은 도메인이니 심플하게 가는 게 좋을 것 같습니다.

https://ko.wikipedia.org/wiki/YAGNI 원칙에 대해서도 읽어보시면 좋을 것 같아요

2024-01-20 08:20 UTC, boy0516 commented on src/main/java/gameboy/gamepack/racinggame/view/ResultView.java
> +    }
TextView 제외했습니다.

2024-01-20 12:06 UTC, nooose requested changes
추가 리뷰드렸습니다. 한번 더 보고 다음 단계 넘어가요~

2024-01-20 12:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/vo/Position.java
> +    }
현재 요구사항으로 봤을 때 음수로 세팅되는 일은 없을 것 같아요
음수가 들어오면 예외를 던지도록 변경할 수 있습니다.
이에 대한 테스트 코드도 있으면 좋겠네요

2024-01-20 12:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/view/InputView.java
> +public class InputView {
테스트 코드에서만 사용되는 것 같습니다.

2024-01-20 12:06 UTC, nooose commented on src/main/java/gameboy/gamepalyer/console/OutputConsole.java
> +public class OutputConsole {
OutputConsole의 역할이 뭘까요?
그냥 표준출력(`System.out.println("문자열")`) 을 호출하는 것과 차이가 없을 것 같아요

InputView나 OutputView가 표준출력을 사용해서 정해진 값들을 입출력하도록 하는 게 좀 더 자연스럽지 않을까요?
```java
int carCount = InputView.inputCarCount();
int tryCount = InputView.inputTryCount();
ResultView.printResult(cars);
```

2024-01-20 12:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/entity/DriverTest.java
> +        }
드라이버 객체에서 위치를 알아내기 위해 Car를 꺼내보고 Car에게 다시 질의하고 있네요
이 자체를 드라이버에게 맡기면 어떨까요?
**디미터 법칙**이라고 검색해 보시면 좋은 글들이 많으니 한번 읽어보시면 도움될거에요

2024-01-20 12:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/entity/RacingTrackTest.java
> +        assertThat(racingTrack.getResult()).size().isEqualTo(driverCount);
결국 자동차 수만 체크하는 것 같은데
`raceOneTime()` 호출과는 상관 없어보입니다.

2024-01-20 12:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/RacingTrack.java
> +    }
`getResult`인데 결과랑 상관없이 Car리스트만 뽑고 있네요
심지어 경주를 진행하지도 않았는데도 getResult()를 언제든지 호출할 수 있어서
클라이언트 쪽에서 헷갈리기만 할 것 같네요

이럴때는 그냥 getCars 로 이름을 변경해서 단순 게터를 사용하는 것이 좋을 것 같습니다.

2024-01-20 12:06 UTC, nooose commented on src/main/java/gameboy/gamepalyer/GamePlayer.java
> +        RacingGamePack racingGame = new RacingGamePack();
게임팩 갈아끼우려면 인터페이스 타입으로 선언하는 게 좋겠네요 🎮
```suggestion
        GamePack racingGame = new RacingGamePack();
```

2024-01-20 12:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/view/ResultView.java
> +        return wheelMark + "\n";
"-".repeat 도 있어요 😄

2024-01-20 12:06 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/view/ResultView.java
> +        carsPosition.stream().forEach(position -> stringBuilder.append(createWheelMark(position)));
문자열을 규칙적으로 이어붙이는 거라면 StringBuilder는 거의 사용하지 않습니다.

자동차마다 이동거리를 만들고 joining 연산으로 합치는게 가독성에 훨씬 좋습니다.
```java
.collect(Collectors.joining("\n")))
```

2024-01-20 12:06 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/entity/RacingTrackTest.java
> +    }
between과 별 차이는 없는 것 같네요 😅

2024-01-20 14:11 UTC, boy0516 commented on src/test/java/gameboy/gamepack/racinggame/data/entity/RacingTrackTest.java
> +    }
혹시 분리해서 해보라는 뜻인가 하는 생각에 😅. 이번걸로 학습차 분리 작업을 해보라는게 아니라는걸 알았으니 다음부턴 좀 더 의미있는 작업으로 하겠습니다.

2024-01-20 14:30 UTC, boy0516 commented on src/main/java/gameboy/gamepalyer/console/OutputConsole.java
> +public class OutputConsole {
view를 gamePack에 종속되는 입출력 데이터라고 정하고
실제 외부 입출력은 gamePalyer패키지에서 진행해야겠다고 정하고 시작해서 입출력을 위임할 console을 따로 둬야겠다고 생각했었는데 필요해지면 그때 추가해야겠네요.
https://ko.wikipedia.org/wiki/YAGNI 원칙 잘 따르겠습니다.

2024-01-20 15:05 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/entity/RacingTrackTest.java
> +    }
제 전달이 애매했나보네요 😅
테스트를 실행해봐야 이동했는지 안했는지를 알 수 있는 상태입니다.
이러면 테스트했다고 보기힘들죠 50%확률로 맞춘거니까요

---

대표적인 예로 시간이 있습니다.
시간 기반으로 아이디를 채번하는 ID 클래스가 있다고 가정합시다.
이 클래스의 생성자 내부를 보면 시간을 생성(`LocalDateTime.now()`)하고 생성된 시간을 기반으로 아이디를 생성합니다.
이러면 매번 테스트마다 달라지게되고 ID도 변하게됩니다.
```java
new Id();  // 테스트 실행할 때 마다 매번 값이 달라짐
```

이 문제를 해결하기 위해서 `LocalDateTime`을 바깥에서 생성하고 해당 객체에 생성자로 넣어주게되면
원하는 ID를 만들 수 있게 됩니다.
```java 
new Id(LocalDateTime.of(2020, 10, 10)); // 테스트를 여러번 실행해도 값이 고정
```

2024-01-20 15:35 UTC, boy0516 commented on src/test/java/gameboy/gamepack/racinggame/data/entity/RacingTrackTest.java
> +    }
아 이해했습니다. 이런식으로 접근하라는거였군요. 수정해서 리뷰 요청하겠습니다.

2024-01-21 12:06 UTC, boy0516 commented on src/main/java/gameboy/gamepalyer/console/OutputConsole.java
> +public class OutputConsole {
입출력 관련해서 console은 제거했습니다. 그런데 출력되는 텍스트값은 따로 모아서 다룰 필요는 없나요? 마지막 커밋은`RacingGamePack`클래스에 입출력 관련 메시지가 하드코딩되어있습니다. 비슷한 예로 예외처리에 쓰는 텍스트도 따로 빼서 관리하진 않는데 따로 관리할까요?

2024-01-21 14:14 UTC, nooose approved these changes
코멘트가 되게 많았는데 정말 고생많으셨습니다.
아쉬운 부분이 있지만 PR이 너무 길어지는 같아서 여기서 머지할게요.
다음 단계에서 더 빡시게 드리겠습니다. 😆

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/RacingGamePack.java
> +            ResultView.display(raceResult);
`startRace()` 와 리턴 타입이 매칭되지 않는 것 같습니다.
경기를 시작했는데 정수를 반환하면 어떤 값인지 잘 모를 것 같아요
결과가 담긴 객체를 만들어서 내보내는 게 맞는 것 같습니다.

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/RacingGamePack.java
> +    private RacingTrack racingTrack;
`play()`에서만 사용하는 것 같은데
멤버변수로 가질 필요가 있을까요?

지역변수와 다를 게 없을 것 같아요

```java
        int driverCount = InputView.inputNumber("자동차 대수는 몇 대 인가요?");
        RacingTrack racingTrack = new RacingTrack(driverCount);

        int raceCount = InputView.inputNumber("시도할 회수는 몇 회 인가요?");
        for (int i = 0; i < raceCount; i++) {
            List<Integer> raceResult = racingTrack.startRace();
            ResultView.display(raceResult);
        }
```

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/Driver.java
> +    private Car car;
```suggestion
    private static final int MOVE_RANGE = 10;
    private static final int MOVE_MIN = 4;

    private final Random random;
    private Car car;
```

관례상 상수와 멤버변수 구분을 위해 개행을 두고
상수를 맨위에 배치하고 그다음 멤버변수를 배치합니다.

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/Driver.java
> +    }
```suggestion
    public Driver() {
        this(new Random());
    }

    public Driver(Random random) {
        this.random = random;
        this.car = new Car();
    }
```

주 생성자 하나를 사용하는 것이 좋습니다.
초기화 로직을 여러번 작성할 필요가 없으니까요 😄

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/RacingTrack.java
> +    }
Integer를 사용한 이유가 있을까요?
primitive 타입을 사용해도 될 것 같아요

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/vo/Position.java
> +    }
이 부분도 래퍼클래스를 사용했네요 🤔

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/RacingTrack.java
> +    }
```java
    public RacingTrack(int driverCount) {
        this(engageDriver(driverCount));
    }

    private static List<Driver> engageDriver(int driverCount) {
        List<Driver> drivers = new ArrayList<>();
        for (int i = 0; i < driverCount; i++) {
            drivers.add(new Driver());
        }
        return drivers;
    }

    public RacingTrack(Driver... drivers) {
        this(List.of(drivers));
    }

    public RacingTrack(List<Driver> drivers) {
        validateDriverCount(drivers);
        this.drivers.addAll(drivers);
    }
```

되도록 생성자는 주 생성자 하나를 바라보고 만드는 게 좋습니다.
그렇지 않으면 중복 로직이 발생하고 유효성 검증도 놓칠 수 있게 됩니다.

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/data/entity/RacingTrack.java
> +        drivers.stream().forEach(Driver::drive);
```suggestion
        drivers.forEach(Driver::drive);
```
forEach는 리스트에서 바로 가능합니다 😄

2024-01-21 14:14 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/view/ResultView.java
> +        return carsPosition.stream().map(ResultView::createWheelMark).collect(Collectors.joining("\n","", "\n"));
```suggestion
        return carsPosition.stream()
        .map(ResultView::createWheelMark)
        .collect(Collectors.joining("\n","", "\n"));
```

코드가 가로로 늘어지면 보기 힘들 수 있습니다.
stream 메서드를 사용할 때는 짧게 짧게 끊어서 읽는 게 더 보기 좋습니다.

2024-01-21 14:14 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/data/entity/RacingTrackTest.java
> +        assertThat(result).size().isEqualTo(driverCount);
`hasSize`로 검증할 수 있습니다.

2024-01-21 14:15 UTC, merged

2024-01-21 15:01 UTC, nooose commented on src/main/java/gameboy/gamepalyer/console/OutputConsole.java
> +public class OutputConsole {
저라면 InputView에게 맡길 것 같습니다.
`InputView.inputGameInfo()`처럼 InputView에 담아둘 수 있을 것 같아요

---

예외처리라면 런타임 예외에 포함되는 메시지를 말씀하시는건가요?