Step1
g-oop/goop-java-racingcar pull request #22
Opened 2024-01-20 08:29 UTC by kimhyoju123

Step1 - 자동차 경주 리뷰 부탁드립니다~!

2024-01-21 10:48 UTC, gilbertlim commented on src/main/java/step1/StringAddCalculator.java
>  public class StringAddCalculator {
자동차 경주 게임과 패키지를 분리해도 좋을 것 같아요.

2024-01-21 10:51 UTC, gilbertlim commented on src/main/java/step1/GameApp.java
> +    public static void main(String[] args) {
자동차가 시도 횟수마다 한 칸씩 움직이지 않네요.

테스트 결과 첨부할게요~
```java
자동차 대수는 몇 대 인가요?
5
시도할 횟수는 몇 회 인가요?
3
실행 결과
-
-
-
-
-

-------
-
-
--------
----------

-------------
----------
-------
--------
----------

-------------
----------
-------
---------------
----------
```

2024-01-21 10:54 UTC, gilbertlim commented on README.md
> +## 요구사항 정리
다음 부터는 Commit Convention을 지키면서
"기능 요구사항별로 commit 하면 좋을 것 같아요."

2024-01-21 11:02 UTC, gilbertlim commented on src/main/java/step1/view/InputView.java
> +        while (true) {
while문이 왜 필요했을까요? 없어도 로직을 수행하는데 문제 없어보여요.

2024-01-21 11:03 UTC, gilbertlim commented on src/main/java/step1/view/InputView.java
> +                System.out.println("숫자만 입력하세요.");
예외로 처리해도 된답니다~

2024-01-21 11:03 UTC, gilbertlim commented on src/main/java/step1/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
상수는 대문자 + 언더바로 !

2024-01-21 11:05 UTC, gilbertlim commented on src/main/java/step1/view/InputView.java
> +        return inputToNum(QUESTION);
상수처리 하지 않아도 좋을 것 같아요. 재사용되지 않기 때문!

2024-01-21 11:06 UTC, gilbertlim commented on src/main/java/step1/view/ResultView.java
> +        ResultView.divideProgressStage();
divideProgressStage();

2024-01-21 11:23 UTC, gilbertlim commented on src/main/java/step1/vo/Cars.java
> +    }
프로덕션 코드가 테스트 코드를 위해 작성되면 안돼요!

2024-01-21 11:25 UTC, gilbertlim commented on src/main/java/step1/vo/Car.java
> +    public void moveForward() {
지금 코드는 항상 앞으로 움직이게 되어있어요. (0일때 제외)
기능 요구사항을 보면 전진 또는 멈춤이에요

2024-01-21 11:31 UTC, gilbertlim commented on src/main/java/step1/vo/Cars.java
> +public class Cars {
일급 컬렉션 👍

2024-01-21 11:33 UTC, gilbertlim commented on src/main/java/step1/vo/Car.java
> +        if (isValid(forwardCount)) {
Valid의 의미는 아닌 것 같아요. 움직일 수 있냐의 의미가 맞을 것 같아요

2024-01-21 11:44 UTC, gilbertlim commented on src/test/java/step1/MoveCarTest.java
> +public class MoveCarTest {
테스트 클래스는 프로덕션 코드와 1:1 매핑되어야 해요.
핵심 역할을 수행하는 메서드는 당연히 테스트 하겠지만
가능하면 모든 public method도 테스트하는 것이 좋습니다.

2024-01-21 11:46 UTC, gilbertlim commented on src/main/java/step1/vo/Car.java
> +    public int getRandom(int bound) {
내부에서만 사용되는 것 같아 private으로 변경해봤는데, warning이 발생해요.
항상 BOUND 상수로 값이 들어오기 때문이에요.

2024-01-21 11:46 UTC, kimhyoju123 commented on src/main/java/step1/view/InputView.java
> +        while (true) {
숫자가 아닌 값을 입력하면 제대로 입력할 때까지 다시 입력받도록 하고 싶었는데 굳이 필요없는 기능이긴 합니다. 
밑의 코멘트처럼 예외 처리 되도록 수정해보겠습니다~!

2024-01-21 11:49 UTC, kimhyoju123 commented on src/main/java/step1/vo/Car.java
> +    public void moveForward() {
앟,, 그러네요,,, 잘못 이해하고 있었습니다. 다시 수정하겠습니다! 감사합니다~~

2024-01-21 11:50 UTC, gilbertlim commented on src/main/java/step1/vo/Car.java
> +        ResultView.drawMoveStatus(loc);
도메인 객체가 UI 로직에 의존하고 있어요.
UI 로직이 변경되면 도메인 로직이 수정되어야 해요.
UI 로직이 도메인을 의존하게 바꿔볼까요?

2024-01-21 11:58 UTC, gilbertlim commented on src/main/java/step1/GameApp.java
> +        Cars cars = CarManager.createCar(carCount);
스태틱 메서드로 생성한 이유가 있을 까요?
CarManager가  Cars를 생성하는 데 밖에서 move하는데 또 Cars를 넣어줘야하네요!

2024-01-21 12:00 UTC, gilbertlim commented on src/test/java/step1/MoveCarTest.java
> +        car.moveForward();
moveForward 내부에 Random 로직이 있어요.
개발자는 입력/출력을 직접 조작하여 테스트할 수 있어야 해요.

2024-01-21 12:01 UTC, gilbertlim commented on src/test/java/step1/MoveCarTest.java
> +        assertTrue(carLoc == initialLoc || carLoc >= greaterThan);
"4이상인 값을 넣었을 때 자동차 위치가 이동 했는 가?"와 같이 테스트할 수 있어야 해요.

2024-01-21 12:04 UTC, gilbertlim commented on src/main/java/step1/CarManager.java
> +            ResultView.divideProgressStage();
여기도 View 의존성이 있네요.

2024-01-21 12:10 UTC, gilbertlim commented on src/main/java/step1/CarManager.java
> +
CarManager의 역할이 모호한 것 같아요:)
자동차를 생성하고, 움직이는 것 처럼 보이는데
자동차를 준비시키고, 경주를 시작하는 역할이 더 직관적일 것 같아요.
스태틱 메서드로 구현하는 것 보다 인스턴스 메서드로 관리하는 것은 어떨까요?
객체의 상태를 직접 관리하면 외부로 부터 객체를 주입받지 않아도 될 것 같아요.

2024-01-21 12:11 UTC, gilbertlim requested changes
이제 본격적인 OOP 시작이네요~
수정사항 반영하고 다시 요청주세요!

2024-01-21 12:34 UTC, kimhyoju123 commented on src/main/java/step1/GameApp.java
> +        Cars cars = CarManager.createCar(carCount);
없습니당,,,😅 수정하겠습니다!

2024-01-27 08:31 UTC, gilbertlim requested changes
수정 후 다시 요청해주세요!

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/GameApp.java
> +        ResultView.printResult(carManager);
👍

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/GameApp.java
> +        }
입력 값에 대한 검증 로직은 입력값을 처리하는 쪽의 책임인 것 같아요.
InputView 클래스에 책임을 부여하고 내부 메서드로 처리해볼까요 ?

그러면 메인 메서드에는 입력 값을 가지고 CarManager를 생성하고 자동차 관련 로직은 CarManager가 처리하게 되는 부분만 남는답니다~
```java
public static void main(String[] args) {
    CarManager carManager = new CarManager(InputView.getCarCount(), InputView.getTryCount());
    carManager.readyToStart();
    ResultView.printResult(carManager);
    }
```

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/GameApp.java
> +            System.exit(0);
예외로 처리하지 않고 System.exit(0) 메서드로 종료 시키네요.
이유가 궁금해요!
그런데 0으로 종료하는 건 정상적인 종료를 의미해요.

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/view/ResultView.java
> +import step1.racingcar.RandomUtils;
???

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/CarManager.java
> +    private final int tryCount;
멤버 변수로 상태를 관리하는 것이 아니면 메서드의 파라미터로 받는 걸 생각해봐요!
지금 Count 변수들은 단순히 참조만 되고 있어요.

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/CarManager.java
> +        cars = new Cars(carList);
멤버변수 초기화를 생성자가 아닌 다른 곳에서 한다는 건 조금 이상해요.

```java
    public CarManager(int carCount) {
        this.cars = new Cars(
            IntStream.range(0, carCount)
                .mapToObj(i -> new Car())
                .toList()
        );
    }
```

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/CarManager.java
> +    }
담아 두었다가 다른 객체에서 필요할 때 제공만 하는군요!

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/CarManager.java
> +    }
Intstream의 iterator를 사용하지 않고 단순 반복만 돌릴 때는 무한 스트림을 생성해서 필요한 반복 수 만큼 제한해서 사용할 수 도 있어요.

```java
Stream.generate(Car::new)
    .limit(carCount)
    .toList()
```

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/vo/Car.java
> +    private int loc;
location?
변수명은 줄여쓰지 않아도 돼요.
https://soo0100.tistory.com/2175

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/vo/Car.java
> +    public void moveIfMovable(int condition) {
그냥 move !
메서드 내부 if 문을 잘 작성해서 가독성이 좋아요.
move 할 수 있는 내부 로직은 move만 알고 있어도 될것 같아요. 지금은 외부로 다 보여지는 것 같아요.

어 ,,, 그런데 움직일 수 있다면 움직여라? 뭔가 당연한 말 같기도..ㅎㅎ

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/vo/Cars.java
> +            .peek(car -> car.moveIfMovable(RandomUtils.getRandom(bound)))
peek() 연산은 어떤 이유로 사용했나요?
스트림 디버깅 용도의 메서드로 많이 쓰는데
forEach가 최종 처리 메서드여서 이후 map을 사용할 수 없기 때문에 썼던 걸까요?

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/view/ResultView.java
> +    public static void printResult(int tryCount, CarManager carManager) {
!!!
UI가 도메인을 의존하는 건 맞는데...
시도 횟수에 따라 자동차를 움직이는 핵심 로직이 UI에 있네요!!
도메인으로 이동이 필요해 보여요

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/view/ResultView.java
> +    public static void printResult(CarManager carManager) {
앞에서 코멘트한 것 처럼 CarManger에서 carCount, tryCount 멤버변수가 빠지면 메서드의 파라미터도 변경되겠네요.

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/vo/Cars.java
> +            .peek(car -> car.moveIfMovable(RandomUtils.getRandom(bound)))
ResultView에서 넣어준 bound 파라미터가 CarManager를 지나 Cars까지 그냥 넘어오네요. bound는 Random과 아주 밀접한 관계로 보이는데 Random에서 직접 관리하는 것은 어떨까요?

2024-01-27 08:31 UTC, gilbertlim commented on src/test/java/step1/racingcar/RacingCarTest.java
> +        assertThat(car.getLoc()).isEqualTo(expected);
테스트 코드를 위한 Getter.
Getter를 사용하지 않고 변경하려면 어떻게 해야할까요? 
객체를 만들면 됩니다. 그리고 Equals 메서드로 비교하는 거죠.

2024-01-27 08:31 UTC, gilbertlim commented on src/main/java/step1/racingcar/vo/Cars.java
> +            .peek(car -> car.moveIfMovable(RandomUtils.getRandom(bound)))
학습 목적으로 랜덤 값을 전략패턴으로 적용해볼까요? 

https://velog.io/@mohai2618/전략-패턴Strategy-Pattern은-무엇인가

2024-01-27 10:25 UTC, kimhyoju123 commented on src/main/java/step1/racingcar/GameApp.java
> +            System.exit(0);
예외 발생하면 바로 종료시키려고 추가했었습니다!

2024-01-27 11:32 UTC, kimhyoju123 commented on src/main/java/step1/racingcar/view/ResultView.java
> +import step1.racingcar.RandomUtils;
😰ResultView에 import RandomUtils가 없어야되는거 맞나요??

2024-01-27 11:54 UTC, kimhyoju123 commented on src/test/java/step1/racingcar/RacingCarTest.java
> +        assertThat(car.getLoc()).isEqualTo(expected);
equals(), hashCode() 를 오버라이딩 해서 비교하면 되는거 맞을까요??

2024-01-27 11:56 UTC, gilbertlim commented on src/main/java/step1/racingcar/view/ResultView.java
> +import step1.racingcar.RandomUtils;
쓰지 않는데 import해서 남겼는데 잘못남겼을까요..?

2024-01-27 12:00 UTC, gilbertlim commented on src/main/java/step1/racingcar/GameApp.java
> +            System.exit(0);
catch문에서 예외를 발생시키면 int를 바로 리턴할 수 있을 거에요!

2024-01-27 12:11 UTC, gilbertlim commented on src/test/java/step1/racingcar/RacingCarTest.java
> +        assertThat(car.getLoc()).isEqualTo(expected);
어 이거 잘못 남긴듯해요 넘어가주세여!

2024-01-27 12:36 UTC, kimhyoju123 commented on src/main/java/step1/racingcar/GameApp.java
> +            System.exit(0);
1번처럼 catch 문에서 예외 발생시키면 Stack Trace가 출력되길래 2번 재귀 호출 방식으로 다시 입력 받도록 수정해봤는데 이렇게 해도 될까요?? (Stack Trace가 안 나게 하고 싶었습니다!)
```
private static int inputToNum(String question) {
        System.out.println(question);
        String input = SCANNER.nextLine();
        try {
            return Integer.parseInt(input);
        } catch (NumberFormatException e) {
            System.out.println("잘못된 값이 입력되었습니다.");
            throw new IllegalArgumentException(); // 1번
            return inputToNum(question); // 2번
        }
    }
```

2024-01-27 12:47 UTC, kimhyoju123 commented on src/main/java/step1/racingcar/view/ResultView.java
> +import step1.racingcar.RandomUtils;
아뇨! 제가 push 할 때 import 제대로 안 지워졌는데 올린 거 같습니다,,ㅎㅎ

2024-01-27 13:05 UTC, gilbertlim commented on src/main/java/step1/racingcar/GameApp.java
> +            System.exit(0);
좋은 것 같아요 무한 루프 보다 재귀 호출이 훨씬 간결하네요

2024-01-27 15:04 UTC, kimhyoju123 commented on src/main/java/step1/racingcar/vo/Cars.java
> +            .peek(car -> car.moveIfMovable(RandomUtils.getRandom(bound)))
네 리턴값을 주려고 하다보니 저렇게 썼었는데 Car에서 move()(= moveIfMovable()) 메소드가 int 리턴하도록 변경해서 moveCars()에서 peek()을 제거하였습니다

2024-01-27 15:05 UTC, kimhyoju123 commented on src/main/java/step1/racingcar/vo/Car.java
> +    private int loc;
positioin으로 수정했습니다

2024-01-27 15:08 UTC, kimhyoju123 commented on src/main/java/step1/racingcar/view/ResultView.java
> +    public static void printResult(int tryCount, CarManager carManager) {
CarManager로 시도 횟수에 따라 자동차 움직이는 로직을 이동시켰는데 view로 화면에 출력하기 위해서 List<List<Integer>> 타입을 썼는데 괜찮을까요??

2024-01-28 06:42 UTC, gilbertlim requested changes
마지막으로 객체의 역할/책임에 대해서 생각해보고 정리만 하면 될 것 같아요.
패키지, 객체의 역할에 대한 코멘트를 남겨두었으니 확인해보고 반영해주세요.

2024-01-28 06:42 UTC, gilbertlim commented on src/main/java/step1/racingcar/view/ResultView.java
> +        });
자동차를 움직이는 로직 moveCars()는 CarManager에 있어요.
그런데 moveCars()를 호출해서 자동차를 움직이게 하는 것이 View에 있어서 이상하다고 말씀드린거였어요. 

CarManager는 자동차를 세팅 후 움직이게 하는 역할이 아닌가요?
현재는 View에서 결과를 뽑기 위해 CarManager를 입력받고 직접 자동차를 움직이고 있어요.

View의 역할은 결국 상태를 담고 있는 객체 Car 혹은 Cars가 출력하는 건데 그것을 래핑하고 있는 객체 CarManager를  받아 관련 로직을 실행시켜서 결과를 얻고 그것을 출력하고 있어요.

2024-01-28 06:42 UTC, gilbertlim commented on src/main/java/step1/racingcar/view/ResultView.java
> +    public static void printResult(int tryCount, CarManager carManager) {
이번 리뷰에 다시 코멘트 달았습니다.

2024-01-28 06:42 UTC, gilbertlim commented on src/main/java/step1/racingcar/view/ResultView.java
> +    public static void printReadyToStart(CarManager carManager) {
CarManager를 파라미터로 받는 것이 아니라 Cars를 받는 것은 어떤가요?
결국 상태를 담고 있는 객체 Car 혹은 Cars가 출력되는 건데 그것을 래핑하고 있는 객체 CarManager가 아니라 CarManager로부터 Car 혹은 Cars객체를 받아서 출력 해도 될 것 같아요.

```java
public static void printReadyToStart(Cars cars) {
    ...
}
```

View에 있는 다른 메서드들도 마찬가지 입니다.

2024-01-28 06:42 UTC, gilbertlim commented on src/main/java/step1/racingcar/GameApp.java
> +public class GameApp {
클래스별로 역할을 정의하는 것은 어떨까요? 
지금 로직 구현은 다 되었는데 관련 로직을 어디서 담당하는지만 결정하고 정리만 하면 될 것같아요.
클래스 마다 몇가지 남겨볼게요.

App은 입력을 받아 CarManager를 생성한다.
그리고 CarManager의 메서드를 호출하여 자동차 경주를 시작한다.

2024-01-28 06:42 UTC, gilbertlim commented on src/main/java/step1/racingcar/CarManager.java
> +public class CarManager {
CarManager를 도메인 패키지 밖으로 꺼내고
View와 Domain 모두 의존하면서 로직을 풀어주는 역할을 수행한다고 해볼까요?

2024-01-28 06:42 UTC, gilbertlim commented on src/main/java/step1/racingcar/vo/Car.java
> +public class Car {
racingcar 하위의 패키지를 두 개만 둬볼게요.
```java
racingcar
ㄴ GameApp
ㄴ CarManager
ㄴview
   ㄴ InputView
   ㄴ ResultView
ㄴ domain
  ㄴ vo 
      ㄴ Car ...
  ㄴ Generator Interface
```

2024-01-28 06:42 UTC, gilbertlim commented on src/main/java/step1/racingcar/util/MovableNumberGenerator.java
> +public class MovableNumberGenerator implements NumberGenerator {
테스트를 위한 구현체들은 테스트 패키지로 이동해야 해요
프로덕션 코드에는 직접 사용할 구현체만 남겨두고요.

2024-01-28 06:42 UTC, gilbertlim commented on src/main/java/step1/racingcar/vo/Car.java
> +    public int move(NumberGenerator numberGenerator) {
인터페이스는 Car에서 의존하는 것이 맞을까요?
car는 단순히 숫자를 입력받아 움직이면 되지 않을까요?
Interface를 의존하는 것은 현재로는 CarManager가 좋을 것 같아요.

우리 실무에서 엔티티 객체가 interface를 의존하지는 않잖아요?

2024-01-28 12:54 UTC, gilbertlim approved these changes
고생하셨습니다.
코멘트 몇 개 남겼어요. 다음 단계 시작 전에 반영해주세요.
다음 단계 진행하세요.

2024-01-28 12:54 UTC, gilbertlim commented on src/main/java/step1/racingcar/CarManager.java
> +        List<Car> carList = Stream.generate(Car::new).limit(carCount).toList();
Stream은 요렇게 하는게 가독성이 좋아보이는데 어떠세요?
```java
Stream.generate(Car::new)
    .limit(carCount)
    .toList();
```

2024-01-28 12:54 UTC, gilbertlim commented on src/main/java/step1/racingcar/CarManager.java
> +            cars.moveCars();
`cars.move()` 가 맞을 것 같습니다! 지금은 "자동차야 자동차를 움직여" 느낌..

2024-01-28 12:54 UTC, gilbertlim commented on src/main/java/step1/racingcar/domain/NumberGenerator.java
> +public interface NumberGenerator {
vo가 전략패턴이 적용된 클래스를 의존하니 어디에 위치할까 고민했겠네요.
여기서 Car와 Cars는 FoMember와 유사해요.
FoMember가 repository에 의존하면 이상하잖아요?
지금 상황에서는 CarManager가 의존하는게 좋을 것 같아요.

그러면 패키지는 아래와 같겠네요.
```java
racingcar
ㄴ domain
ㄴ view
ㄴ strategy
   ㄴ *Generator
```

2024-01-28 12:54 UTC, gilbertlim commented on src/main/java/step1/racingcar/GameApp.java
> +        CarManager carManager = new CarManager(InputView.getCarCount());
CarManager가 의존하게 하려면 아래와 같이 해야해요
```java
CarManager carmanager = new CarManager(InputView.getCarCount, new RandomNumberGeneratorI());
```

2024-01-28 12:54 UTC, gilbertlim commented on src/test/java/step1/racingcar/ImmovableNumberGenerator.java
> +        return 3;
항상 정지하는 조건👍

2024-01-28 12:54 UTC, merged

2024-01-28 13:35 UTC, kimhyoju123 commented on src/main/java/step1/racingcar/CarManager.java
> +        List<Car> carList = Stream.generate(Car::new).limit(carCount).toList();
option + Cmd + L 단축키 써서 저렇게 됐었던 것 같습니다. 다시 수정해두겠습니다!