3단계 - 자동차 경주 🚘
g-oop/goop-java-racingcar pull request #23
Opened 2024-01-21 04:59 UTC by mzueon

리뷰 부탁드립니다~!

2024-01-21 12:21 UTC, gilbertlim commented on README.md
> +## 기능목록
👍

2024-01-21 12:24 UTC, gilbertlim commented on src/test/java/racingcar/domain/car/DefaultCarTest.java
> +        numberGenerator = mock(RandomNumberGenerator.class);
Mockito를 사용해서 직접적으로 테스트할 수 없는 랜덤을 제어하고 있네요.
Mocking 없이 테스트하려면 어떻게 해야할까요?
개발자는 input/output을 직접 모두 핸들링할 수 있어야 해요!

2024-01-21 12:26 UTC, gilbertlim commented on src/test/java/racingcar/domain/game/RacingGameInitializerTest.java
> +        view = mock(RacingGameView.class);
"모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외"

2024-01-21 12:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGame.java
> +    private final RacingGameView view;
도메인 객체가  UI에 의존하고 있어요.
UI가 바뀌면 도메인 로직이 영향을 받아요.

UI 로직이 도메인 객체를 주입받아 처리할 수 있게 변경해볼까요?

2024-01-21 12:30 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGameInitializer.java
> +    private final RacingGameView view;
도메인 객체가 UI에 의존!

2024-01-21 12:37 UTC, gilbertlim commented on src/main/java/racingcar/view/InputView.java
> +        while (true) {
while 문을 사용한 이유가 있을까요? 바로 return해서 반복의 의미는 없어보이네요.
INVALID 값일 경우 예외를 발생시켜도 좋을 것 같아요.

2024-01-21 12:42 UTC, gilbertlim commented on src/main/java/racingcar/view/RacingGameView.java
> +    private final InputView inputView;
InputView를 주입받는 이유가 있을까요?
static으로 사용해도 문제 없어 보여요! 뭐가 더 나을 지 고민해볼까요?

2024-01-21 12:43 UTC, gilbertlim commented on src/main/java/racingcar/view/RacingGameView.java
> +        System.out.print("⛟");
👍x 100

2024-01-21 12:59 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGameInitializer.java
> +    public RacingGame init(){
RacingGameInitializer는 view를 의존하여 입력 값을 사용하여 RacingGame 객체를 생성하는 역할 밖에 없어보여요.
도메인 객체에서 view 관련된 로직이 빠지게 되면 Initializer의 역할이 모호해질 수 있어요.
이렇게 연쇄적인 의존관계가 있었기 때문에 GameApplication에서 new(new()) 와 같은 형태를 띄었군요.

2024-01-21 13:02 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGameInitializer.java
> +        return new RacingGame(new RacingGameSetting(cars, attemptCount), view);
RacingGameSetting은 단순히 DTO의 역할로 보여요. 같은 패키지 레벨의 도메인 객체 간에 DTO가 필요한 지 고민해볼 필요가 있어요.

2024-01-21 13:07 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGameInitializer.java
> +    private List<Car> createCars(int carCount){
자동차를 생성하는 로직의 위치가 올바른 지 고민해볼까요?
자동차를 move하는 메서드는 RacingGame에 있어요.
관련 로직들이 뭉쳐지면 코드가 단순해질 수 도 있어요.

2024-01-21 13:08 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/Game.java
> +public interface Game {
Game 인터페이스를 사용한 이유는 무엇인가요 ? 단순한 질문이에요.

2024-01-21 13:09 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/RandomNumberGenerator.java
> +    }
테스트 코드를 위한 프로덕션 코드는 올바르지 않아요.
생성자, 단순 getter는 괜찮은데 Setter는 고민해볼 필요가 있답니다.

2024-01-21 13:10 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/RandomNumberGenerator.java
> +    private int bound;
bound를 인스턴스 변수로 사용하는 이유는 무엇이었나요?
setter 때문이었나요?

2024-01-21 13:17 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/Car.java
> +public interface Car {
여기도 인터페이스로 구현한 이유가 궁금해요!

2024-01-21 13:18 UTC, gilbertlim commented on src/main/java/racingcar/application/GameApplication.java
> +        game.start();
initializer가 init하여 game을 생성하고
game이 시작하는 구조네요.

game이 직접 init하고 start하는 것도 괜찮을 것 같은 데 어떻게 생각하시나요 ?

2024-01-21 13:25 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/DefaultCar.java
> +    }
사용하지 않는 생성자네요~?

2024-01-21 13:31 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/DefaultCar.java
> +        if (numberGenerator.generate() >= MOVE_THRESHOLD){
isMovable() 같은 메서드로 분리하는 것은 어떨까요? 문법 맞나요..?

2024-01-21 13:34 UTC, gilbertlim requested changes
이제 본격적인 OOP 시작!
코멘트 남겼으니 확인해주세요!
리뷰 재요청 부탁드려요:)

2024-02-08 01:28 UTC, yamsroun commented
@mzueon 수정 반영 안된지 오래되었네요~
2월 말까지 얼마 안 남았어요~
조금만 더 달려봅시당~ ⛟⛟⛟⛟⛟⛟⛟⛟⛟⛟⛟

2024-02-09 06:30 UTC, mzueon commented on src/main/java/racingcar/domain/game/Game.java
> +public interface Game {
사실 특별한 이유는 없습니다.. 다만 제가 어떻게 구현할지 상상을 하다가, 닌텐도처럼 게임칩을 바꿔가면서 게임을 실행하는 느낌을 내보고 싶어서,,, 그래서 인터페이스를 써봤습니다..

2024-02-09 06:34 UTC, mzueon commented on src/main/java/racingcar/domain/car/RandomNumberGenerator.java
> +    private int bound;
저는 이 클래스를 일종의 자동차 부품(?) 처럼 생각하고 작성했습니다! 그래서 1~10까지 숫자를 생성하는 게 기본이지만, 원한다면 1~bound까지 생성할 수 있도록 설정할 수 있게 하고 싶어서 bound를 사용해봤습니다 ㅎㅎ..

2024-02-09 06:38 UTC, mzueon commented on src/main/java/racingcar/domain/car/Car.java
> +public interface Car {
이것도 사실 큰 의미는 없고 그냥 제가 상상하다가 이렇게 구현하게 된 것인데요, 자동차 경주 게임이니까 자동차 종류가 여러가지 있을 수도 있지 않을까 싶어서 인터페이스를 작성했습니다.  
위에 코멘트 남겨주신 코드와 연관 있기도 합니다. 자동차 종류별로 내부에 들어가는 랜덤 숫자 생성기의 bound를 다르게 설정하는 상상을 했었습니다...

2024-02-09 06:43 UTC, mzueon commented on src/main/java/racingcar/application/GameApplication.java
> +        game.start();
제가 생각했던 방식은 Game은 게임 그 자체의 로직(?)만 가지고 있게 하고 싶었습니다! 그래서 자동차 경주의 경우, 자동차를 생성하거나 사용자의 입력값을 받는 등의 로직은 제외하고 자동차가 움직이는 기능 자체만 game이 관리하게 하고 싶었습니다. 
약간 게임 시작할 때 캐릭터 생성하는 부분이랑 실제로 게임 스토리를 진행하는 부분이랑 구분시켜놓는,, 그런 느낌이었는데 생각해보니 구분시켜도 의미가 없는 것 같긴 하네요..

2024-02-09 06:48 UTC, mzueon commented on src/main/java/racingcar/view/InputView.java
> +        while (true) {
이상한 값을 입력하면 영원히 게임속에 갇히도록 하려고 했는데.. 보내줘야겠군요

2024-02-11 23:29 UTC, gilbertlim requested changes
코멘트 확인 후 재요청해주세요!

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/DefaultCar.java
> +        this.position = 0;
생성자에서 초기 값을 지정하는 경우 주 생성자, 부생성자 방식을 추천드려요.

주 생성자는 private로 정의해도 되겠네요.

```suggestion
        this(name, 0);
```

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/DefaultCar.java
> +    private final RandomNumberGenerator numberGenerator;
랜덤 값을 생성하는 로직이 Car의 역할인지 고민이 필요해요.
그리고 지금 구조에서는 RandomNumberGenerator가 변경되면 Car 인터페이스를 확장하여 구현한 클래스들이 모두 영향을 받아요.
랜덤 값 생성이 Car의 역할이 아니라면, 의존성을 제거해야할거에요.

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/DefaultCar.java
> +    }
랜덤 값 생성 로직을 외부로 이동시키면 아래와 같이 변경될 수 있겠네요.

```suggestion
    public void move(int number) {
        if (isMovable(number)){
            position++;
        }
    }
```

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGame.java
> +public class RacingGame implements Game {
인터페이스 구조로 개발한 이유를 물었던 건 아래와 같은 원칙 때문이었어요.
고민해보시고 필요하면 적용해도 괜찮을 것 같아요.
(현 상태 유지 or 인터페이스 제거)

https://en.m.wikipedia.org/wiki/You_aren%27t_gonna_need_it

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGame.java
> +        RacingGameView view = new RacingGameView(this);
RacingGame은 RacingGameView를 의존하고 있네요.
그런데 RacingGameView도 RacingGame을 의존하고 있어요.

양방향 의존 관계는 로직이 변경되면 두 클래스를 항상 수정해야 하며, 추후 클래스를 분리하기 어려워요.

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGame.java
> +            view.printCurrentStatus();
RacingGameView를 의존하지 말고, RacingGameView가 Car를 의존하게 하는 건 어떨까요?

```suggestion
            RacingGameView.printCurrentStatus(cars);
```

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/view/RacingGameView.java
> +    }
입력/출력 로직이 하나의 클래스에 있었네요.
두 로직을 클래스로 분리하는 것은 어떨까요?

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGame.java
> +        this.attempts = view.getAttemptCount();
인스턴스 변수를 초기화 하는 로직은 생성자를 통해 하는 것이 어떨까요?

어디서 변수를 초기화하는 지 생성자 외 메서드를 모두 확인해야해서 가독성이 떨어질 수 있어요.

private method로 선언해서 외부에서 호출될 일은 없을 수 있겠지만요..

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGame.java
> +    private void race(RacingGameView view){
System In으로 입력받는 값은 멤버 변수로 관리하지 않고, 외부에서 원시 값으로 받아도 괜찮을 것 같은데요?

```suggestion
    private void race(int attempts){
```

2024-02-11 23:29 UTC, gilbertlim commented on src/main/java/racingcar/domain/game/RacingGame.java
> +    private List<Car> createCars(int carCount){
cars 초기화는 생성자,
Generator는 move 메서드로 이동되겠네요.

2024-02-12 15:00 UTC, mzueon commented on src/main/java/racingcar/domain/car/DefaultCar.java
> +    private final RandomNumberGenerator numberGenerator;
혹시 이 부분은 조금만 더 설명해주실 수 있으실까요? 
저는 랜덤값 생성 로직을 Car에서부터 분리하고자 하는 목적으로 RandomNumberGenerator를 생성했었거든요.. RandomNumberGenerator가 인터페이스라서 실제 구체적인 로직은 RandomNumberGenerator 를 구현하는 클래스가 가지고 있다고 생각했습니다. 그래서 Car는 RandomNumberGenerator 를 주입받아서 단순히 메서드를 사용하기만 하면 되지 않을까 싶었었는데, 이런식으로 주입받아서 사용하는 것도 로직을 포함하게 되는건가요? (라고 쓰다보니 아무래도 그렇겠구나 라는 생각이 문득 들긴 합니다.. 아무래도 제가 의존(?)의 개념을 혼동하고 있는 것 같습니다ㅎ;;)

그리고 또 궁금한 점이, RandomNumberGenerator가 변경되면 Car 인터페이스에 대한 구현클래스들이 모두 영향을 받게 되는 이유가 무엇인가요? RandomNumberGenerator가 변경이 필요하면, 내부적인 로직을 수정하기 위해서 구체클래스만 수정하면 되도록 하고 싶어서 인터페이스로 작성한 것이었거든요.. 아니면 말씀하신 RandomNumberGenerator의 변경이 해당 인터페이스 자체의 변경을 말씀하시는 걸까요??

2024-02-13 12:05 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/DefaultCar.java
> +    private final RandomNumberGenerator numberGenerator;
이전 코드에서 Car 객체를 생성할 때 인자로 generator를 넣어주도록 되어있었는 데, 그 부분이 Car가 랜덤값 생성을 위한 인터페이스를 의존한다는 말이었어요.
도메인 객체가 어쨋든 랜덤이라는 존재를 알고 있으니까요.

그리고 자동차가 **스스로** 랜덤 값을 (인터페이스를 통해) 생성하고 움직일 수 있으면 움직이는 로직이 조금 직관적이지 않았다고 할까요? (이건 좀 억지일 수도 있어요..🥲)

2024-02-13 12:21 UTC, gilbertlim approved these changes
코멘트 남겼어요. 확인하고 다음 단계 진행해주세요!

2024-02-13 12:21 UTC, gilbertlim commented on src/main/java/racingcar/domain/car/Car.java
> +    }
주 생성자가 아래로 위치하는 것이 관례라고 해요!

2024-02-13 12:21 UTC, gilbertlim commented on src/test/java/racingcar/domain/car/CarTest.java
> +        car.move(MoveRandomNumberGenerator.generate());
테스트를 위한 구현체라면 테스트 패키지러 이동해도 좋을 것 같아요!

2024-02-13 12:22 UTC, merged

2024-02-13 13:25 UTC, mzueon commented on src/main/java/racingcar/domain/car/DefaultCar.java
> +    private final RandomNumberGenerator numberGenerator;
그 전까지는 generator를 Car와 일종의 한 쌍(?) 처럼 생각을 하고 있었더니, 이 부분 때문에 코드 작성할 때 좀 힘들었습니다.. 이제 생각해보니 제가 두 클래스 사이 의존관계를 만들어 놔서 서로 영향을 주고 있었기 때문인 것 같아요! 말씀해주신 대로 아예 분리하고 나니 로직을 구성하는 게 훨씬 쉬워지더라구요!! 그리고 저는 인터페이스는 아무튼 일단 써도 괜찮겠거니 하는 생각이 있었는데, 불필요한 사용으로 인해 오히려 복잡하게 느껴졌던 것 같네요.. 짚어주시지 않으셨다면 계속 몰랐을 것 같습니다 ㅎ..
상세한 리뷰 감사드립니다! 👍🏻