Step3
g-oop/goop-java-racingcar pull request #25
Opened 2024-01-21 10:13 UTC by parksuja

2024-01-21 14:36 UTC, gilbertlim requested changes

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/util/InputHandler.java
> +public interface InputHandler {
Interface로 구현한 이유는 무엇인가요 ?

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/util/RacingCarInputHandler.java
> +        while (true) {
무한 루프를 사용한 이유는 무엇인가요 ?

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/util/RacingCarInputHandler.java
> +                scanner.nextLine();
nextInt() 이후 nextLine()을 사용한 이유는 무엇인가요?

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/util/RacingCarInputHandler.java
> +    public String getCarNameFromUser(String message) {
이름을 입력하는 요구사항은 없는데 추가된 이유는 무엇인가요?

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/util/RacingCarInputHandler.java
> +        return carName;
다음과 같이 리팩토링할 수 있을 것 같아요.
```java
        String carName = "DefaultCar";
        try {
            System.out.print(message);
            carName = scanner.nextLine();
        } catch (NoSuchElementException e) {
        }

        return carName;
```

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/ui/RacingGame.java
> +public class RacingGame implements Game{
"자바 코드 컨벤션을 지키면서 프로그래밍한다."
프로그래밍 요구사항을 지켜주세요. 이외에도 많이 보이네요.

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/ui/Game.java
> +public interface Game {
인터페이스를 사용한 이유가 무엇인가요 ?

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/util/RacingCarInputHandler.java
> +public class RacingCarInputHandler implements InputHandler{
ui와 관련된 클래스에요. ui 패키지 하위로 가는 것이 좋지 않을까요?
util은 공통 코드의 의미를 가지고 있는데 패키지화할 필요가 있는 지, 필요하다면 어떤 이름으로 변경해야할 지 고민이 필요해요.

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/RacingcarApplication.java
> +        RacingGame racingGame = new RacingGame();
view 로직이 외부로 드러나 있지 않다는 것은 RacingGame 도메인 객체가 view에 의존하고 있다는 것을 의미해요. 도메인은 UI 로직을 몰라야 합니다. UI 로직이 바뀌게 되면 도메인 전체가 영향을 받을 수 있어요.

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/ui/RacingGame.java
> +    private void getCountFromUser() {
get 메서드인데 상태를 변경하네요.  메서드명을 고민해봐야할 것 같아요.

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/ui/RacingGame.java
> +        initializeCars(carCount);
UI 로직은 도메인 밖에 있어야 의존성이 분리됩니다.

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/ui/RacingGame.java
> +    }
UI 로직 중 결과 로직에 해당되네요.

프로그래밍 요구사항을 반영해주세요.
- 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.
- UI 로직을 InputView, ResultView와 같은 클래스를 추가해 분리한다.

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +        return state.toString();
StringBuilder 없이도 구현 가능해 보여요. 
```java
return "|" + "-".repeat(position) + ">";
```
그런데 이것도 UI 로직인데 도메인 객체 내에 있네요

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +        int randomNumber = new Random().nextInt(10);
현재 구조로는 Random을 테스트할 수 없어요. 고민해볼까요?
랜덤 값 입력을 직접 개발자가 컨트롤할 수 있어야 해요!

2024-01-21 14:36 UTC, gilbertlim commented on src/test/java/RacingGameTest.java
> +        assertTrue(car.getPosition() == initialPosition + 1 || car.getPosition() == initialPosition);
항상 성공하는 테스트에요.

랜덤 입력을 직접 컨트롤 할 수 있어야해요. 한 번 고민 해보시죠!

2024-01-21 14:36 UTC, gilbertlim commented on src/test/java/RacingGameTest.java
> +        System.setIn(new ByteArrayInputStream(simulatedInput.getBytes()));
모든 로직에 단위 테스트를 구현한다. 단, UI(System.out, System.in) 로직은 제외

2024-01-21 14:36 UTC, gilbertlim commented on src/test/java/RacingGameTest.java
> +public class RacingGameTest {
테스트 코드는 프로덕션 클래스와 1:1 매핑되어야 합니다.
그리고 모든 public 메서드를 테스트하는 것이 좋아요!

2024-01-21 14:36 UTC, gilbertlim commented on src/main/java/domain/ui/RacingGame.java
> +    private OutputHandler outputHandler;
UI 로직 분리

2024-01-21 14:37 UTC, gilbertlim commented
이제 본격적인 OOP 시작!

코멘트 반영 후 다시 리뷰 요청해주세요~~!

2024-01-21 14:52 UTC, parksuja commented on src/main/java/domain/util/RacingCarInputHandler.java
> +                scanner.nextLine();
scanner.nextLine();없이는 
자동차 이름을 입력하세요: 자동차 이름을 입력하세요: 라고 뜨길래 넣어줬습니다.

2024-01-21 14:52 UTC, parksuja commented on src/main/java/domain/util/RacingCarInputHandler.java
> +    public String getCarNameFromUser(String message) {
쉽게 분리할려고 이름을 추가하면서 테스트 했었습니다.

2024-01-21 14:53 UTC, parksuja commented on src/main/java/domain/util/RacingCarInputHandler.java
> +        while (true) {
이거는 무조건 try catch돌려고 했었습니다.

2024-01-21 14:54 UTC, parksuja commented on src/main/java/domain/util/InputHandler.java
> +public interface InputHandler {
이거는 InputHandler여러개 쓰일거를 대비해서 한거였습니다. 바꾸겠습니다.

2024-01-21 14:55 UTC, parksuja commented on src/test/java/RacingGameTest.java
> +        System.setIn(new ByteArrayInputStream(simulatedInput.getBytes()));
죄송합니다.. 잘 못봤습니다.

2024-01-27 04:51 UTC, gilbertlim commented on src/main/java/domain/ui/InputProvider.java
> +package domain.ui;
ui 패키지는 도메인 밖으로 옮겨볼까요 ?

2024-01-27 05:41 UTC, gilbertlim requested changes
피드백 확인 후 다시 리뷰를 요청해주세요.

지금 1차 피드백 반영 커밋이 1개에요. 커밋을 나누는 습관이 필요해 보입니다.
커밋 메시지를 Conventions에 따라 나눠볼까요? 
커밋은 말그대로 커밋이에요. 완벽할 필요 없고 실수 했다면 `fix` 로 수정해도 된답니다.

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/ui/InputProvider.java
> +package domain.ui;
ui 패키지는 도메인 밖으로 옮겨볼까요 ?

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/ui/InputProvider.java
> +public interface InputProvider {
처음 부터 인터페이스로 개발하는 이유는 무엇인가요 ?
무조건 확장 가능한 코드를 작성하는 것은 오버엔지니어링이에요.
https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/ui/OutputResult.java
> +    public void printCarStates(List<Car> cars) {
이런식으로 UI 메서드는 도메인 객체를 파라미터로 받으면 돼요.

도메인은 UI를 모르게 해야해요.

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/RacingcarApplication.java
> +public class RacingcarApplication {
테스트는 통과하는데 애플리케이션을 실행하면 요구사항을 충족하는 결과가 나오지 않습니다.

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +        this.random = new Random();
random 멤버 변수가 없는데 어떻게 초기화 할까요? PR 전에 컴파일 및 테스트 코드 확인, 동작 확인은 필수입니다.

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/Game.java
> +public interface Game {
확장성 관련 코멘트는 이미 달아 두었습니다.

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +    private final OutputProvider outputProvider;
멤버변수로 강결합시키지 않아도 될 것 같습니다.

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +    public void play() {
메서드의 파라미터로도 처리가능할 것 같아요.
```java
public void play(InputProvider inputProvider, OutputProvider outputProvider) {
```

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +        outputProvider.printCarStates(cars);
moveCars()에서도 동일한 메서드를 호출하고 있어요.

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +            int randomNumber = generateRandom(RANGE_NUMBER);
randomNumber 생성을 반복문 앞에서 하셨네요. 뒤에 있는 모든 자동차의 인자로 들어가는 값이 같을 것 같은데요?

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +            }
시도 횟수 반복문과 메서드를 분리할 수 있을 것 같아요.
이중 for 문을 메서드로 분리가능해보입니다.
그러면 원래 moveCars의 메서드명을 변경해야될 수 있겠네요.

```java

moveCars();
```

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +        return new Random().nextInt(number);
generateRandom 메서드가 반복문 안에서 호출돼요. 호출될 때마다 Random 인스턴스를 생성하는 데 인스턴스 생성은 한 번만 하고, 랜덤 값만 반복문 안에서 뽑아도 되지 않을 까요?

2024-01-27 05:41 UTC, gilbertlim commented on src/test/java/RacingGameTest.java
> +        Assertions.assertThat(car.getPosition()).isEqualTo(position + 1);
테스트 코드에서만 Getter가 사용되네요.
equals 메서드로 위치 값을 비교해볼까요?

https://mangkyu.tistory.com/101

2024-01-27 05:41 UTC, gilbertlim commented on src/main/java/domain/ui/InputResult.java
> +                System.out.println("유효하지 않은 입력입니다. 정수를 입력하세요.");
음수 값, 0 등 입력에 대한 추가 검증을 해보는 건 어떨까요?

2024-01-27 13:27 UTC, parksuja commented on src/main/java/domain/ui/InputProvider.java
> +public interface InputProvider {
OOP 의존성 역전 원칙을 통해 객체가 아닌 추상화에 의존해야한다는 법칙을 위해 interface를 사용했습니다.

2024-01-27 13:27 UTC, parksuja commented on src/main/java/domain/ui/InputProvider.java
> +public interface InputProvider {
일단 class로 로직 올렸습니다. interface없이

2024-01-27 13:29 UTC, parksuja commented on src/main/java/domain/Car.java
> +        this.random = new Random();
이전 커밋이 올라갔습니다. 해당 건은 변경했습니다.

2024-01-27 13:29 UTC, parksuja commented on src/main/java/domain/ui/InputProvider.java
> +package domain.ui;
넵 반영했습니다.

2024-01-27 13:36 UTC, parksuja commented on src/main/java/domain/Game.java
> +public interface Game {
넵 반영했습니다. 나중에 Game이라는 구현체가 바뀔수도있기떄문에 interface를 임시로 써놨던거였습니다. 
해당 Interface주석했습니다.

2024-01-28 06:49 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +public class RacingGame {
RacingGame이 UI와 도메인을 모두 의존하면서 로직을 풀어조는 역할이라면 패키지 위치가 domain, ui 내부가 아니여야 해요.

2024-01-28 06:51 UTC, gilbertlim commented on src/test/java/RacingGameTest.java
> +    public void MoveWithRandomNumberGreaterThanEqual4(int randmomNumber) {
이 부분은 getPosition()으로 위치값을 비교하도록 다시 변경해주세요.
잘못 가이드 드렸네요 ;
아래 메서드도 마찬가지입니다.

2024-01-28 06:52 UTC, gilbertlim commented on src/main/java/ui/InputResult.java
> +                } else {
이번 미션에서 else를 쓰지 않는 것이 요구사항이에요.

2024-01-28 06:52 UTC, gilbertlim commented on src/main/java/ui/OutputProvider.java
> +//}
불필요한 클래스는 주석이 아니라 삭제하는 것이 어떨까요?

2024-01-28 07:15 UTC, gilbertlim requested changes
코멘트 확인 후 재요청해주세요!

2024-01-28 07:15 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +    private final OutputResult outputResult;
play에 파라미터로 받아왔으니 멤버 변수로는 관리하지 않아도 되지 않을까요?

2024-01-28 07:15 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +public class RacingGame {
RacingGame이 UI와 도메인을 모두 의존하면서 로직을 풀어조는 역할이라면 패키지 위치가 domain, ui 내부가 아니여야 해요.

2024-01-28 07:15 UTC, gilbertlim commented on src/main/java/ui/OutputProvider.java
> +//package ui;
불필요한 클래스는 주석이 아니라 삭제하는 것이 어떨까요?

2024-01-28 07:15 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +    public void initializeCars(int carCount) {
cars를 초기화하는 부분이니 생성자에서 구현해도 될 것 같아요.

2024-01-28 07:15 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +        return new Random().nextInt(RANGE_NUMBER);
전략 패턴으로 랜덤 값을 사용하도록 변경해볼까요 ?

https://velog.io/@mohai2618/전략-패턴Strategy-Pattern은-무엇인가

2024-01-28 07:15 UTC, gilbertlim commented on src/main/java/domain/RacingGame.java
> +            positions[i] = cars.get(i).getPosition();
stream으로 처리해보는 것도 좋을 것 같아요

2024-01-29 10:04 UTC, merged