Step3
g-oop/goop-java-racingcar pull request #26
Opened 2024-01-21 15:41 UTC by mz-bskoo

리뷰 부탁드립니다.

2024-01-27 06:19 UTC, yamsroun requested changes
코드를 정말 깔끔하게 잘 짜셨네요~ 👍🏾👍🏾👍🏾
제가 코멘트 남긴 내용은 대부분 사소한 것들이지만, "Request changes"로 한번 날려봤습니다.

2024-01-27 06:19 UTC, yamsroun commented on src/test/java/com/megazone/goop/racingcar/logic/CarTest.java
> +        assertThat(car.move(randValue)).isEqualTo(1);
테스트 코드에서 `Car` 객체의 `move()`의 반환값이 무엇인지 명확하게 표현하면 더 좋을 것 같습니다.
저는 "이동한 거리"로 이해했습니다.
로컬 변수로 추출해서 변수명에 의미를 부여하면 더 명확해질 수 있습니다.
```suggestion
        int moveDistance = 1;
        assertThat(car.move(randValue)).isEqualTo(moveDistance);
```

2024-01-27 06:19 UTC, yamsroun commented on src/test/java/com/megazone/goop/racingcar/logic/CarTest.java
> +        assertThat(car.move(randValue)).isEqualTo(0);
SonarLint 짱짱맨~
```suggestion
        assertThat(car.move(randValue)).isZero();
```

2024-01-27 06:19 UTC, yamsroun commented on src/test/java/com/megazone/goop/racingcar/logic/CarTest.java
> +class CarTest {
다른 테스트 코드에서 다른 목적으로 호출하고는 있지만,
`CarTest` 코드에 `getTotalDistance()`의 테스트 코드도 들어가면 더 좋겠습니다.

2024-01-27 06:19 UTC, yamsroun commented on src/main/java/com/megazone/goop/racingcar/logic/Car.java
> +        }
👍🏾

2024-01-27 06:19 UTC, yamsroun commented on src/main/java/com/megazone/goop/racingcar/logic/Race.java
> +    }
생성자에서 사용하는 메서드이므로 생성자 메서드 바로 다음에 위치시키면 어떨까요?

2024-01-27 06:19 UTC, yamsroun commented on src/main/java/com/megazone/goop/racingcar/logic/Race.java
> +    }
하나의 `Race` 객체에서 `startRace()`를 2번 이상 호출하면 의도한 결과가 나오지 않을 것 같습니다.

2024-01-27 06:19 UTC, yamsroun commented on src/main/java/com/megazone/goop/racingcar/logic/Race.java
> +    private ArrayList<Car> cars;
변수의 타입은, 클래스 상속 계층에서 의미를 모호하게 만들지 않는 가장 높은 수준의 타입을 선택하는 것이 일반적으로 좋습니다.
* `ArrayList` -> `List`

여기서, `List`의 상위 타입인 `Collection`을 사용하면 타입의 의미를 모호하게 만듭니다.

2024-01-27 06:19 UTC, yamsroun commented on src/test/java/com/megazone/goop/racingcar/logic/RandomGeneratorTest.java
> +    void randomBetweenTest(int value) {
`value` 파라미터 변수를 사용하고 있지 않습니다.

2024-01-27 06:19 UTC, yamsroun commented on src/test/java/com/megazone/goop/racingcar/logic/RandomGeneratorTest.java
> +        assertThat(randomGenerator.getRandomValue(bound)).isGreaterThanOrEqualTo(0);
SonarLint 짱짱맨~
```suggestion
        assertThat(randomGenerator.getRandomValue(bound)).isNotNegative();
```

2024-01-27 06:19 UTC, yamsroun commented on src/test/java/com/megazone/goop/racingcar/logic/RandomGeneratorTest.java
> +        assertThat(randomGenerator.getRandomValue(bound)).isLessThanOrEqualTo(9);
동일한 actual에 대한 다중 expect 체크는 메서드를 체인하는 것이 가독성에 더 좋습니다.
```suggestion
        assertThat(randomGenerator.getRandomValue(bound))
            .isNotNegative()
            .isLessThanOrEqualTo(9);
```

2024-01-28 05:28 UTC, mz-bskoo commented on src/test/java/com/megazone/goop/racingcar/logic/CarTest.java
> +class CarTest {
네.. 좋은 의견이십니다.
어떤 테스트 코드 항목들을 추출해야 할지 좀 어려웠던 것 같습니다.

2024-01-28 06:17 UTC, mz-bskoo commented on src/main/java/com/megazone/goop/racingcar/logic/Car.java
> +        }
감사합니다.

2024-01-28 06:50 UTC, mz-bskoo commented on src/main/java/com/megazone/goop/racingcar/logic/Race.java
> +    }
레이스를 시작하기 전에 초기화 하는 코드를 추가하여 보완하였습니다.

2024-01-28 07:20 UTC, mz-bskoo commented on src/test/java/com/megazone/goop/racingcar/logic/RandomGeneratorTest.java
> +        assertThat(randomGenerator.getRandomValue(bound)).isLessThanOrEqualTo(9);
네~~ 훨씬 깔끔하고 정리된 코드가 되었습니다.

2024-01-28 10:59 UTC, yamsroun approved these changes
고생하셨습니다~
다음 단계로 넘어가시면 됩니당~

2024-01-28 11:00 UTC, merged