4단계 - 자동차 경주(우승자) - 요구사항 반영
g-oop/goop-java-racingcar pull request #28
Opened 2024-01-28 12:33 UTC by yamsroun

2024-01-28 14:53 UTC, nooose requested changes
불변천국이네요..
리뷰 남긴 것 중에 몇개만 해결하면 될 것 같습니다.
궁금해서 질문 남긴 것도있는데 답변 부탁드립니다. 🙇

2024-01-28 14:53 UTC, nooose commented on src/main/java/racingcar/racing/RacingEntries.java
> +    public List<Car> getWinners() {
멱등성있게 구현하셨네요 👍

2024-01-28 14:53 UTC, nooose commented on src/main/java/racingcar/racing/RacingEntries.java
> +    public List<Car> getWinners() {
`getWinners()`를 호출할 때 마다 
`maxPosition`과, `winners`가 초기화될텐데 멤버변수가 불필요할 것 같아요
지역변수로 써도되지 않나요?

2024-01-28 14:53 UTC, nooose commented on src/main/java/racingcar/entry/CarName.java
> +public record CarName(String value) {
👍

2024-01-28 14:53 UTC, nooose commented on src/main/java/racingcar/entry/CarPosition.java
>  public class CarPosition {
CarName은 record를 사용했는데
CarPosition은 record를 사용하지 않았네요 
이유가 있나요?

2024-01-28 14:53 UTC, nooose commented on src/main/java/racingcar/racing/RacingPreference.java
> +    String[] carNames,
배열보다는 리스트가 편의측면에서 좋을 것 같습니다.

2024-01-28 14:53 UTC, nooose commented on src/main/java/racingcar/ui/ConsoleRacingUi.java
>  public class ConsoleRacingUi implements RacingUi {
리뷰남기려고 아무 클래스나 찍어서 올릴게요 이 클래스는 무시해주세요 😅

---
몇 가지 문제가 있어보입니다.

<img width="619" alt="image" src="https://github.com/g-oop/goop-java-racingcar/assets/36617783/ce3c8ff9-0a08-4ffa-aaf6-80fede481559">

<img width="664" alt="image" src="https://github.com/g-oop/goop-java-racingcar/assets/36617783/09acd1f7-cc54-4474-afad-de41aeca4236">

<img width="673" alt="image" src="https://github.com/g-oop/goop-java-racingcar/assets/36617783/950a9955-4458-4875-95c4-36d46e3eb7f1">


😄

2024-01-29 13:27 UTC, yamsroun commented on src/main/java/racingcar/racing/RacingEntries.java
> +    public List<Car> getWinners() {
지역변수를 사용해도 됩니다.
처음에는 지역변수를 사용했다가, 클래스 분리 빌드-업을 해나가는 과정이었습니당~😅

`RacingEntries` 클래스
```java
public List<Car> getWinners() {
    RacingWinners racingWinners = new RacingWinners(this.cars);
    return racingWinners.getWinners();
}
```

`RacingWinners` 클래스
```java
public class RacingWinners {

    private final List<Car> cars;
    private final List<Car> winners = new ArrayList<>();
    private int maxPosition = 0;

    public RacingWinners(List<Car> cars) {
        this.cars = cars;
    }

    public List<Car> getWinners() { ... }

    private int addWinnerAndGetNewMaxPosition(Car car) { ... }
}
```

아래 글 참고해 주세용~
https://velog.io/@csh0034/Clean-Code-10%EC%9E%A5-%ED%81%B4%EB%9E%98%EC%8A%A4
<img width="816" alt="image" src="https://github.com/g-oop/goop-java-racingcar/assets/20655591/72311899-85eb-4d63-a252-39802e3cb097">

2024-01-29 13:30 UTC, yamsroun commented on src/main/java/racingcar/entry/CarPosition.java
>  public class CarPosition {
그러게요. 왜 그랬을까요.
이 눔의 IntellJ한테 시달리다 보니..😅

2024-01-29 14:23 UTC, yamsroun commented
코드 리뷰 반영했습니다.
슬랙 메시지는 인자한 쌤인데, PR 메시지는 호랑이 쌤이네요~
덕분에 많이 배우고 있습니다.
계속 호랑이 쌤이 되어주세요~😍😍😍

2024-01-29 15:17 UTC, nooose commented on src/main/java/racingcar/racing/RacingEntries.java
> +    public List<Car> getWinners() {
역시나 이런 깊은 뜻이있었군요..

2024-01-29 15:43 UTC, nooose approved these changes
왜 그런지 모르겠는데 어느 순간 제가 🐯가 되었네요..

다음은 마지막 5단계인데요
사실 1~4 단계 하시면서 5단계 요구사항들을 모두 반영하셨습니다. 
너무 깔끔해서 리뷰드릴 부분도 없고 그래서
다음 단계는 생략하고 여기서 멈춰도 될 것 같습니다.
바로 로또 해도 될 것 같네요 ㅋㅋ (귀찮아서 끝내는 거 절대! 아님)

2024-01-29 15:43 UTC, nooose commented on src/test/java/racingcar/racing/RacingEntriesTest.java
> +        List<String> carNames = List.of("yamsr", "gilbe", "nooos", "yamsr");
😂

2024-01-29 15:43 UTC, nooose commented on src/main/java/racingcar/entry/CarPosition.java
>      }
```suggestion
    public Position increase() {
        return new Position(position + 1);
    }
```

불변이니까 증가된 값을 줘도 될 것 같아요

2024-01-29 15:43 UTC, nooose commented on src/test/java/racingcar/entry/CarTest.java
>      }
CarName 클래스를 테스트해도 좋았을 것 같습니다.

2024-01-29 15:43 UTC, nooose commented on src/main/java/racingcar/racing/RacingEntries.java
> +            .map(String::trim)
trim은 입력 관련 클래스에서 처리하고 넘겨받아도 좋았을 것 같아요

2024-01-29 15:43 UTC, merged

2024-02-05 14:30 UTC, yamsroun commented on src/main/java/racingcar/entry/CarPosition.java
>      }
넹~😍

2024-02-05 14:35 UTC, yamsroun commented on src/test/java/racingcar/entry/CarTest.java
>      }
넹😍

2024-02-05 15:41 UTC, yamsroun commented on src/main/java/racingcar/racing/RacingEntries.java
> +            .map(String::trim)
넹🥰