5단계 - 자동차경주(리팩토링)
g-oop/goop-java-racingcar pull request #32
Opened 2024-01-30 14:12 UTC by boy0516

5단계 리뷰 부탁드립니다.🙇🏻‍♂️

2024-01-30 14:14 UTC, boy0516 commented
근데 이렇게 하는게 맞나요;;? 패키지만 바꿨는데

2024-01-30 16:36 UTC, nooose requested changes
네 맞습니다

5단계에서 다 바꾸려고하면 구조 전체가 변경될 수 있어서 
아마 지훈님이 미션 던지기를 시전할까봐 
1~4 단계부터 제가 일부러 중간중간 5단계에 할 피드백을 하나씩 풀어드렸습니다.

피드백 조금 남겼는데 저 부분만 하고 마무리할게요

2024-01-30 16:36 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/domain/data/dto/RaceResultDto.java
> +    }
이전 질문에 대한 저의 의견입니다.

정적 팩토리 메소드를 사용하는 이유는 주로 다음과 같습니다.
1. 이름을 가질 수 있음
 - 생성자를 정확히 몰라도 이름으로 유추하여 생성이 가능 

다른 이유도 있으니 검색해 보시면 많은 글들이 나옵니다.

지금 구조로 봤을 때는 of라는 이름을 가져서 어떤 장점을 가져오나요?
`new RaceResultDto(RaceLog리스트, Car리스트)`로 생성하는 것과 똑같아 보입니다.

예시를 들어볼게요
```java
Car entity = // 생성;
CarResponse.from(entity) // DTO 변환
```
코드를 봤을 때 from 메소드를 보면 해당 객체로 부터 응답객체를 생성하는구나 하고 알 수 있습니다.

```java
// 정적 팩토리 메소드 잘못된 예시 
new CarResponse(car.id, car.name, car.age, ...) 
CarResponse.from(car.id, car.name, car.age, ...) // 결국 생성자와 동일, 불필요함

// O
CarResponse.from(car) 
```

2024-01-30 16:36 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/domain/data/entity/CarMovement.java
> +        return new Position(position.value());
```suggestion
        return position;
```
그대로 넘겨도 될 것 같아요

2024-01-30 16:36 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/domain/data/vo/Position.java
>      }
멤버변수를 +1 증감하고 새로운 객체를 반환하네요
증감했다면 void 타입을 사용해도 되었을 것이고
그게 아니라면 상태를 변경하지 않고 +1 한 값을 만들어서 리턴하는 방법 둘중 1개가 있을텐데
두가지가 혼용된 것 같아요. 

```java
Position position = new Position(1);
newPosition = position.addOne();

position.eqauls(newPosition) // 같음
```

제가 이해한게 맞나요?

2024-01-30 16:36 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/domain/data/entity/CarMovementTest.java
> +        CarMovement car = new CarMovement(new TestRandom(randomInt));
자동차 정지 테스트라기보다는 위치 판단용인 것 같아요
자동차 주행을 테스트하려면 `car.run()` 메소드를 수행해야 할 것 같네요

---

그리고 Movement 인터페이스를 만드셨으니 랜덤에 의존적인 테스트보다는
AlwaysMovement, StopMovement 같은 구현체를 만들어서 테스트하는 것이 더 좋을 것 같네요

2024-01-30 16:36 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/domain/data/vo/RaceLog.java
> +public class RaceLog {
이정도면 record 써도될 것 같아요
게터나 생성자 보일러플레이트 코드도 사라지겠네요

2024-01-31 03:57 UTC, boy0516 commented on src/main/java/gameboy/gamepack/racinggame/domain/data/entity/CarMovement.java
> +        return new Position(position.value());
그대로 넘겨주면 최종 출력값에 오류가 있습니다. 제 생각엔 position을 그대로 반환하면 이동하지 않았을 때 새로 생성된 car에서 position을 그대로 참조하고있어서 결과 출력할때 최종 위치가 나옵니다.

2024-01-31 04:02 UTC, boy0516 commented on src/main/java/gameboy/gamepack/racinggame/domain/data/entity/CarMovement.java
> +        return new Position(position.value());
음.. 다시 보니까 불변클레스인데 불변이 아니게 코드가 짜여있는거같아요. 좀 더 보고 수정하겠습니다.

2024-01-31 16:32 UTC, nooose approved these changes
수고하셨습니다. 👍 많은 인사이트 얻어 가셨길 바랍니다!

2024-01-31 16:32 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/domain/data/dto/RaceResultDto.java
>      }
전달이 제대로 안 되었나보네요 🥲
이 부분도 마찬가지 
`new RaceResultDto(raceLogs, winners)`를 호출하는 것과 차이가 없어보입니다.

생성자 사용을 피하는 이유가 있으신가요?

2024-01-31 16:32 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/domain/data/entity/RacingTrack.java
>          }
요구사항은 아니지만
`racingTrack.startRace(raceCount);`를 한번 더 수행하는 경우
경기가 이어지는데 이런 부분들도 멱등성있게 구현하면 좋습니다.

2024-01-31 16:32 UTC, nooose commented on src/main/java/gameboy/gamepack/racinggame/domain/data/vo/Position.java
> +    }
이 생성자는 프로덕션 코드에서 사용되지 않으므로 제거하는 것이 좋겠네요
테스트 코드에서는 `Position(0)`을 사용해도 될 것 같아요

2024-01-31 16:32 UTC, nooose commented on src/test/java/gameboy/gamepack/racinggame/domain/data/entity/AlwaysStopCar.java
> +public class AlwaysStopCar extends Car {
run 내부 동작을 override 하고 있네요 
run 동작을 온전하게 테스트하기보다는 동작 전체를 갈아끼운 듯한 느낌이 듭니다.

우리가 테스트해야할 부분은 랜덤입니다. 
랜덤같이 제어 불가능한 영역을 제어할 수 있게 하고 나머지 코드는 온전하게 놔두는 것이 핵심입니다.

그렇기 때문에 Car는 그대로 두고 전략만 갈아끼우면 됩니다. 
Car를 생성할 때 전략을 Car에다가 넣어주는 방법입니다.
```java
Car car = new Car(name, alwaysMovement);
car.run();
```
위 방법도 좋지만 멤버변수를 갖게되고 생성 시 넣어줘야합니다.

다음은 메소드에 전략을 전달하는 방법이 있습니다.
```
car.run(alwaysMovement);
```

https://github.com/yamsroun-Study/goop-java-racingcar/blob/step4/src/main/java/racingcar/entry/Car.java 
@yamsroun 팀장님의 코드이니 
어떻게 테스트를 했는지도 참고해 보시면 좋겠네요

2024-01-31 16:33 UTC, merged