4단계 - 자동차 경주(우승자)
g-oop/goop-java-racingcar pull request #33
Opened 2024-01-30 15:09 UTC by parksuja

2024-01-31 00:28 UTC, gilbertlim requested changes
고생하셨어요!
미션을 빠르게 진행하는 것도 좋지만 어느 정도는 꼼꼼하게 개발하는 습관이 중요해요. 매번 언급할 수 없어서 지켜 보다가 아직도 코드 상으로 꼼꼼하지 않은 부분이 나타나고 있어 조언을 남겨요. 하나 하나 의미를 따져보고 고민하는 과정도 매우 중요해요.

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
> +        String[] carNames = carNameFromUser.split(",");
comma로 구분된 자동차명을 파싱하는 로직은 어느 클래스의 역할일까요? view로직에 해당된다고 생각해요.
view 로직으로 옮겨볼까요?

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
> +        List<String> determineWinners = new ArrayList<>();
컬렉션 변수명이 동사로 시작하네요?

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
>              generateRandomValue();
메서드명 변경이 필요해요.
랜덤 값을 생성한다는데, 자동차도 움직이네요. 

학습 차원으로 모든 클래스, 변수명, 메서드명을 검토하고 적절히 수정할까요?

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
> +            List<String> winners = determineWinner(getCarNames(), getCarPositions());
시도 횟수마다 우승자를 계산하네요?
마지막에 우승자를 계산하는 것이 경제적일 것 같아요.

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
> +            List<String> winners = determineWinner(getCarNames(), getCarPositions());
컬렉션타입 변수 cars만 넘겨줘도 될 것 같아요.

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/ui/InputResult.java
> +            if (carName.trim().isEmpty()) {
indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/ui/OutputResult.java
> +    private static List<String> getWinners(String[] carNames, int[] positions, int maxPosition) {
여기도 cars를 넘기고 stream으로 계산해도 될 것 같아요.

2024-01-31 00:28 UTC, gilbertlim commented on src/test/java/RacingGameTest.java
>          if (randomValue <= 3) {
테스트 코드에서 조건문을 사용하는 것이 아니라
전략 패턴을 적용한 인터페이스를 테스트용도로 구현해볼까요?
무조건 정지하는 조건의 숫자를 반환하는 구현체, 무조건 움직이는 조건의 숫자를 반환하는 구현체
TC는 나눠야 할거 같아요.

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +    private String name;
학습 목적으로 name 변수를 래핑해볼까요?
그리고 이름 관련된 로직은 래핑한 객체로 모두 옮겨보세요.

```suggestion
    private CarName name;
```

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/domain/Car.java
>      private int position;
학습 목적으로 postion 변수도 래핑해볼까요?

```java
private Position position
```

2024-01-31 00:28 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
>      private static final int RANGE_NUMBER = 10;
랜덤 관련 상수는 랜덤 관련 클래스로 옮겨도 될 것 같아요.

2024-01-31 15:40 UTC, gilbertlim requested changes
중간 리뷰 완료

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/domain/Car.java
>      public Car() {
Car 객체는 VO(CarName, Position)를 멤버변수로 가지고 있어요. 불변으로 관리한다는 것을 의미하고 항상 의도된(=valid) 상태라는 것을 보장할 수 있어요. 빈 생성자를 호출하면 VO는 null이 됩니다.  의도한게 아니라면 삭제!

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +        this(name, 0);
부생성자 👍🏼

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +    public Car(String name, int position) {
주 생성자는 외부로 노출될 필요가 없다면 private로 처리해도 좋아요. 항상 부생성자를 타고 초기화 됨을 의미하게돼요.

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +            position.increment();
increase

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/domain/vo/CarName.java
> +        return name.length() > MAX_LENGTH;
이 조건은 valid가 아닌거 같아요.

```suggestion
        return name.length() <= MAX_LENGTH;
```

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/domain/vo/CarName.java
> +        if (isValid(name)) {
메서드명이 이상해요. valid 한데 예외를 터뜨리네요

```suggestion
        if (!isValid(name)) {
```

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/domain/vo/Position.java
> +        if (isValid(position)) {
🥲

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/domain/vo/Position.java
> +        return position < MIN_VALUE;
🥲

2024-01-31 15:40 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
>      private static final int RANGE_NUMBER = 10;
😢

2024-02-01 00:26 UTC, parksuja commented on src/main/java/service/RacingGame.java
>      private static final int RANGE_NUMBER = 10;
public class NumberGeneratorImpl implements NumberGenerator {

    public static final Random RANDOM = new Random();
    private static final int RANGE_NUMBER = 10;


    @Override
    public int generateRandomValue() {
        return RANDOM.nextInt(RANGE_NUMBER);
    }
}

RANGE_NUMBER를 리턴할떄 받으면 사용자가 제어할수없지않나요? NumberGeneratorImpl클래스에서 사용하면?

2024-02-01 00:26 UTC, parksuja commented on src/main/java/domain/Car.java
> +        this(name, 0);
👍

2024-02-01 15:37 UTC, gilbertlim requested changes
간단히 수정할 내용 적어 봤어요.

다음 미션 시작 전에 먼저 반영해주세요.
+ 다음 미션에서는 학습 목적으로 Cars 라는 일급컬렉션을 사용해볼까요?

그럼, 다음 미션 진행하세요!

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +    private Position position;
final !

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/domain/Car.java
> +    public void stop() {
사용하지 않는 메서드

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
> +    public void initializeCars(String[] carNames) {
private 메서드로 변경하고 private 메서드를 호출하는 public 메서드 아래에 두는게 가독성이 좋아요!

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/service/RacingGame.java
>          for (int move = 0; move < tryCount; move++) {
for문 내부 iterator 변수는 현재 의미가 없어요. i로 사용해도 무방할듯 합니다.

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/strategy/MovementStrategy.java
> +public interface MovementStrategy {
NumberGenerator 인터페이스를 사용해도 무방해요

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/strategy/MoveMovementStrategy.java
> +public class MoveMovementStrategy implements MovementStrategy {
NumberGenerator을 구현하도록 변경하고, AlwaysReturn5Generator 와 같은 이름을 사용하는 것은 어떨까요?

그리고 테스트 코드를 위한 클래스니까 테스트 패키지로 이동하시죠!
test > java > strategy

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/strategy/StopMovementStrategy.java
> +public class StopMovementStrategy implements MovementStrategy {
이전 구현체에 남긴 코멘트를 참고해서 같이 변경해주세요.

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/ui/InputResult.java
>      private static final Scanner scanner = new Scanner(System.in);
상수명은 대문자 혹은 언더바로 작성하는 것이 관례에요.

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/ui/InputResult.java
>      }
불필요한 메서드 분리라고 생각합니다.

```java
public int getTryCount() {
        System.out.println("시도할 회수는 몇 회 인가요?");
        String input = scanner.nextLine();
        try {
            return Integer.parseInt(input);
        } catch (NumberFormatException e) {
            System.out.println("유효하지 않은 입력입니다. 정수를 입력하세요.");
        }
        return getTryCount();
    }
```

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/ui/InputResult.java
> +        return carNames;
바로 리턴 가능하네요~

```java
return scanner.nextLine().trim().split(",");
```

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/RacingcarApplication.java
>  public class RacingcarApplication {
RacingCarApplication

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/RacingcarApplication.java
>          int tryCount = inputResult.getTryCount();
static method로 사용해도 좋을 것 같아요.

```java
String[] carNames = InputResult.getCarNameFromUser();
int tryCount = InputResult.getTryCount();
```

2024-02-01 15:37 UTC, gilbertlim commented on src/main/java/domain/vo/Position.java
> +        validatePosition(position);
Position 객체의 테스트 코드는 없네요!

2024-02-01 15:37 UTC, gilbertlim commented on src/test/java/strategy/MovementStrategyTest.java
> +        car.move(stopValue);
아래와 같이 테스트 해보는 것을 의도한 거였어요!
RacingGameTest에 들어가야겠네요.

테스트 코드는 특별한 일이 없다면 프로덕션 패키지 구조와 동일하게 하고
원칙적으로는 모든 public method를 테스트해야 안전합니다. (getter, void 등 제외)

```java
RacingGame racingGame = new RacingGame(new AlwaysReturn0Generator(), new String[] {"a", "b", "c"});
List<String> winnerNames = racingGame.play(5);

// 항상 0이 나오니까 모두 제자리에 있을 것임. 그래서 우승자는 모두
assertThat(winnerNames).contains("a");
assertThat(winnerNames).contains("b");
assertThat(winnerNames).contains("c");
```

2024-02-01 15:38 UTC, gilbertlim approved these changes

2024-02-01 15:39 UTC, merged