2단계 - 문자열 덧셈 계산기
g-oop/goop-java-racingcar pull request #6
Opened 2024-01-09 15:18 UTC by k1m743hyun

@gilbertlim 
리뷰 요청드립니다!

2024-01-10 14:53 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +    @ParameterizedTest
empty string 입력 테스트가 누락 되었네요.

2024-01-10 14:54 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +    @CsvSource(value = {"|0", "1,2|3", "1,2,3|6", "1,2:3|6", "//;\\n1;2;3|6"}, delimiter = '|')
테스트 케이스를 명확히 메서드 단위로 구분할 필요가 있어 보여요.
중복 테스트도 보입니다.

2024-01-10 14:55 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +        StringAddCalculator calculator = new StringAddCalculator(inputString);
StringAddCalculator 인스턴스 생성 시 입력 값을 인자로 받는 것이 좋은 방법일까요?
입력 값이 달라질 때 마다 인스턴스를 생성해야할 것 같아요 🥲

2024-01-10 14:57 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +        Assertions.assertThat(calculator.add()).isEqualTo(result);
add() 메서드의 역할도 모호해졌어요. 무엇을 더하는 지 알 수 없어요.

2024-01-10 14:58 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +    @ValueSource(strings = {"a", "-1", "//|\\n1|s|3",  "//;\\n1;-2;3"})
디테일한 테스트 케이스 👍

2024-01-10 15:02 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    public StringAddCalculator(String inputString) {
생성자의 역할에 대해 살펴볼 필요가 있어요. 생성자에 역할은 객체 초기화에요!

2024-01-10 15:03 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    private String inputString;
멤버 변수로 관리할 필요가 있을 까요? 😯

2024-01-10 15:06 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +        }
생성자에 있는 로직이 빠지면 하나의 메서드에 많은 역할이 부여될 수 있어요. 프로그래밍 요구사항을 고려해서 설계해보세요.

2024-01-10 15:09 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    public int add() {
add 메서드가 너무 많은 일을 하고 있어요.

2024-01-10 15:11 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +        for (String s : inputString.split(delimiter == null ? "[,:]" : delimiter)) {
삼항 연산자가 인라인으로 되어 있어 가독성에 영향을 주는 것 같아보여요.

2024-01-10 15:16 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +        Assertions.assertThatThrownBy(calculator::add).isInstanceOf(RuntimeException.class);
숫자 이외의 값과 음수 값에 대한 에러 메시지를 별도로 확인해보는 것은 어떨까요?

2024-01-10 15:27 UTC, gilbertlim commented
코멘트를 확인하고 재요청 해주세요.

2024-01-11 00:30 UTC, k1m743hyun commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +    @ParameterizedTest
delimiter 앞이 empty string이고 결과 값이 0이어야 해서 "|0"으로 입력한 건데
단순히 ""이면 결과 값을 알 수 없지 않나요??

2024-01-11 00:32 UTC, k1m743hyun commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +    @CsvSource(value = {"|0", "1,2|3", "1,2,3|6", "1,2:3|6", "//;\\n1;2;3|6"}, delimiter = '|')
앞에 요구사항도 만족해야 하기 때문에 중간에 코드가 바뀌면 앞의 요구사항을 놓치는 경우가 있을 수 있어서
앞에서도 사용한 테스트 케이스를 사용했습니다.
모두 만족한 거 확인했으니 중복되는 케이스는 지우겠습니다!

2024-01-11 00:37 UTC, k1m743hyun commented on src/main/java/racingcar/StringAddCalculator.java
> +    private String inputString;
멤버 변수로 관리하지 않으면 객체를 생성하는 의미가 없는 거 같은데요,,,
그러면 객체 생성 없이 코드 작성하는 것이 더 효율적으로 보입니다

2024-01-11 04:11 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +    @ParameterizedTest
"|0" 인 경우 null과 0이 반환됩니다 :)

2024-01-11 13:31 UTC, k1m743hyun commented
@gilbertlim 
리뷰해주신 내용 반영하였습니다
다시 리뷰 부탁드립니다!

2024-01-13 12:51 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +public class StringAddCalculator {
전체적으로 메서드 분리가 필요합니다. 2단계 핵심은 메서드 분리에요.

2024-01-13 13:19 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +        Assertions.assertThat(calculator.splitAndSum(resultMap.get("delimiter"), resultMap.get("inputString"))).isEqualTo(result);
- parse() 반환 값을 splitAndSum()에 인자로 넘겨야 계산 결과가 나오는데 메서드 간 관계를 명확히 알 수 없어 보여요.
- 메서드 간 관계가 계산기 외부로 꼭 노출되어야 할까요?
- 또 매 번 "delimiter", "inputString"을 입력해야 하는데... API를 사용하는 측면에서 다시 고려해볼만 한 요소입니다.

2024-01-13 13:25 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +        Map<String, String> resultMap = new HashMap<>();
Map 사용을 다시 한번 고려해보세요.
- resultMap은 단순히 결과 값을 담는 변수로 보입니다. 어떤 용도로 사용했을까요?
- 입력되는 Key는 두 개로 보이는 데 지역 변수 2개를 사용하는 것과 무엇이 더 간결할까요?
- put 메서드를 사용할 때 key를 하드코딩해서 입력하는 부분도 많이 보이구요.

2024-01-13 13:36 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +        StringAddCalculator calculator = new StringAddCalculator();
계산기를 사용할 때마다 Instance를 생성하는 방식이 좋은 방법인지 고민이 필요합니다.
static method로 구현하는 방법도 있습니다. 고민하는 과정이 필요해요.

2024-01-13 13:47 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    public int splitAndSum(String delimiter, String inputString) {
split과 sum, 그리고 숫자 변환까지 세 가지 기능을 하는 메서드입니다. 최대한 분리하려고 노력해보세요.

2024-01-13 13:50 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +            try {
try... catch문이 for loop 밖으로 이동해도 될 것 같아요.
split() 메서드는 예외를 반환하지 않으니까 예외를 catch하는데 영향을 주지는 않을 것 같아요.

2024-01-13 13:52 UTC, gilbertlim commented
메서드 분리를 중점으로 의견드렸습니다. 수정 후 다시 리뷰 요청해주세요 :)

2024-01-14 07:22 UTC, gilbertlim requested changes
메서드 분리를 중점으로 의견드렸습니다. 수정 후 다시 리뷰 요청해주세요 :)

2024-01-14 09:39 UTC, k1m743hyun commented
@gilbertlim
리뷰해주신 내용 반영하였습니다
다시 리뷰 부탁드립니다!

2024-01-14 09:58 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    private static Matcher getMatcher(String inputString) {
private 메서드는 public 메서드에서 호출되는 순서에 맞게 배치하는 것이 가독성 향상에 도움을 줍니다!

2024-01-14 10:20 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +public class StringAddCalculator {
메서드 마다 null or empty string 입력에 대한 처리 로직이 중복으로 사용되는 경우가 있네요.
```java
if (matcher != null) {}
if (inputString != null) {}
if (inputStrings.length == 0) {}
```

splitAndSum 메서드 앞 단에서 한 번만 체크해주면 될 것 같아서 isNullOrBlank() 메서드를 추가해봤습니다. 테스트는 무사히 통과하네요~
```suggestions
    public static int splitAndSum(String inputString) {
        if (isNullOrBlank(inputString)) {
            return 0;
        }
```

```suggestions
public class StringAddCalculator {

    public static int splitAndSum(String inputString) {
        if (isNullOrBlank(inputString)) {
            return 0;
        }

        String delimiter = getDelimiter(inputString);

        String[] result = splitString(delimiter, inputString);

        return sumStrings(result);
    }

    private static boolean isNullOrBlank(String inputString) {
        return inputString == null || inputString.isBlank();
    }

    private static Matcher getMatcher(String inputString) {
        return Pattern.compile("//(.+)\\\\n(.+)").matcher(inputString);
    }

    private static String getDelimiter(String inputString) {
        String delimiter = "[,:]";
        Matcher matcher = getMatcher(inputString);
        if (matcher.find()){
            delimiter = matcher.group(1);
        }
        return delimiter;
    }

    private static String[] splitString(String delimiter, String inputString) {
        String[] result;
        Matcher matcher = getMatcher(inputString);
        if (matcher.find()) {
            result = matcher.group(2).split(delimiter);
        } else {
            result = inputString.split(delimiter);
        }
        return result;
    }

    private static int parseInt(String s) {

        int i;

        try {
            i = Integer.parseInt(s);
        } catch (NumberFormatException e) {
            throw new RuntimeException("숫자가 아닌 값이 입력되었습니다.");
        }

        if (i < 0) throw new RuntimeException("음수는 입력될 수 없습니다.");

        return i;
    }

    private static int sumStrings(String[] inputStrings) {
        int sum = 0;
        for (String s : inputStrings) {
            sum += parseInt(s);
        }
        return sum;
    }
}
```

2024-01-14 10:22 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +        if (inputString != null) matcher = Pattern.compile("\\/\\/(.+)\\\\n(.+)").matcher(inputString);
compile 메서드는 내부적으로 Pattern 객체를 생성합니다. 상수 처리하여 캐싱해두면 비용을 아낄 수 있어요!

2024-01-14 10:36 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    public static int splitAndSum(String inputString) {
메서드 마다 null or empty string 입력에 대한 처리 로직이 중복으로 사용되는 경우가 있네요.
```java
if (matcher != null) {}
if (inputString != null) {}
if (inputStrings.length == 0) {}
```

splitAndSum 메서드 앞 단에서 한 번만 체크해주면 될 것 같아서 isNullOrBlank() 메서드를 추가해봤습니다. 위에서 언급한 로직은 제거했어요. 테스트는 무사히 통과하네요~
```suggestions
    public static int splitAndSum(String inputString) {
        if (isNullOrBlank(inputString)) {
            return 0;
        }
```

```suggestions
    public static int splitAndSum(String inputString) {
        if (isNullOrBlank(inputString)) {
            return 0;
        }

        String delimiter = getDelimiter(inputString);

        String[] result = splitString(delimiter, inputString);

        return sumStrings(result);
    }

2024-01-14 10:39 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    }
값을 바로 return할 수 있게 되었네요.

private static Matcher getMatcher(String inputString) {
return CUSTOM_DELIMITER_PATTERN.matcher(inputString);
}

2024-01-14 10:40 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    }
null or empty 체크를 앞에서 한 번 했기 때문에 이후 메서드에서 관련 로직을 제거할 수 있어요.

```suggestions
    private static String getDelimiter(String inputString) {
        String delimiter = "[,:]";
        Matcher matcher = getMatcher(inputString);
        if (matcher.find()){
            delimiter = matcher.group(1);
        }
        return delimiter;
    }
```

2024-01-14 10:40 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    }
```suggestions
    private static String[] splitString(String delimiter, String inputString) {
        Matcher matcher = getMatcher(inputString);
        if (matcher.find()) {
            inputString = matcher.group(2);
        }
        return inputString.split(delimiter);
    }
``

2024-01-14 10:50 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    }
```suggestions
    private static int sumStrings(String[] inputStrings) {
        int sum = 0;
        for (String s : inputStrings) {
            sum += parseInt(s);
        }
        return sum;
    }
```

2024-01-14 10:51 UTC, gilbertlim commented on src/main/java/racingcar/StringAddCalculator.java
> +    }
```suggestions
private static int parseInt(String inputString) {
        int number;
        try {
            number = Integer.parseInt(inputString);
            validateNegativeNumber(number);
        } catch (NumberFormatException e) {
            throw new RuntimeException("숫자가 아닌 값이 입력되었습니다.");
        }
        return number;
    }

    private static void validateNegativeNumber(int number) {
        if (number < 0) throw new RuntimeException("음수는 입력될 수 없습니다.");
    }
```

2024-01-14 10:57 UTC, gilbertlim commented on src/test/java/racingcar/StringAddCalculatorTest.java
> +
"" 입력을 처리하는 프로덕션 코드는 있으나 테스트가 누락되었네요.

```java
@NullAndEmptySource
@ParameterizedTest
void null_or_empty_string_입력(String inputString) {
    Assertions.assertThat(StringAddCalculator.splitAndSum(inputString)).isEqualTo(0);
}
```

2024-01-14 10:59 UTC, gilbertlim approved these changes
2단계 고생 많으셨습니다.
메서드를 분리하면서 고생한 흔적이 보이네요.

학습 차원에서 태현님이 작성한 코드를 리팩토링 해봤습니다.
필요한 경우 다음 단계 첫 번째 커밋에 반영해주세요 ~

3단계 미션 시작하시면 됩니다!

2024-01-14 10:59 UTC, merged